
# This file is automatically generated, you probably don't want to edit this

alluvialSurvivalOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "alluvialSurvivalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            timeVar = NULL, ...) {

            super$initialize(
                package="jsurvival",
                name="alluvialSurvival",
                requiresData=FALSE,
                ...)

            private$..timeVar <- jmvcore::OptionVariable$new(
                "timeVar",
                timeVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))

            self$.addOption(private$..timeVar)
        }),
    active = list(
        timeVar = function() private$..timeVar$value),
    private = list(
        ..timeVar = NA)
)

alluvialSurvivalResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "alluvialSurvivalResults",
    inherit = jmvcore::Group,
    active = list(
        mydataview = function() private$.items[["mydataview"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Treatment Pathway Alluvial Plot")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mydataview",
                title="mydataview"))}))

alluvialSurvivalBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "alluvialSurvivalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jsurvival",
                name = "alluvialSurvival",
                version = c(1,0,0),
                options = options,
                results = alluvialSurvivalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Treatment Pathway Alluvial Plot
#'
#' 
#' @param timeVar The name of the time variable in the dataset
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$mydataview} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
alluvialSurvival <- function(
    timeVar) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("alluvialSurvival requires jmvcore to be installed (restart may be required)")

    if ( ! missing(timeVar)) timeVar <- jmvcore::resolveQuo(jmvcore::enquo(timeVar))

    options <- alluvialSurvivalOptions$new(
        timeVar = timeVar)

    analysis <- alluvialSurvivalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

