# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'colorectal' so R CMD check does not flag undocumented data.
#' colorectal: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 700 rows and 8 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{age}{numeric variable}
#'   \item{sex}{factor variable}
#'   \item{old_stage}{ordered/factor variable}
#'   \item{new_stage}{ordered/factor variable}
#'   \item{survival_time}{numeric variable}
#'   \item{event}{integer variable}
#'   \item{cancer_type}{factor variable}
#' }
#' @keywords datasets internal
"colorectal"

