# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'lassocox_cardiovascular' so R CMD check does not flag undocumented data.
#' lassocox_cardiovascular: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 150 rows and 19 variables:
#' \describe{
#'   \item{subject_id}{character variable}
#'   \item{time_to_event_months}{numeric variable}
#'   \item{cv_event}{factor variable}
#'   \item{age_years}{numeric variable}
#'   \item{gender}{factor variable}
#'   \item{race_ethnicity}{factor variable}
#'   \item{bmi_kg_m2}{numeric variable}
#'   \item{systolic_bp_mmhg}{numeric variable}
#'   \item{diastolic_bp_mmhg}{numeric variable}
#'   \item{total_cholesterol_mg_dl}{numeric variable}
#'   \item{hdl_cholesterol_mg_dl}{numeric variable}
#'   \item{ldl_cholesterol_mg_dl}{numeric variable}
#'   \item{diabetes_mellitus}{factor variable}
#'   \item{hypertension}{factor variable}
#'   \item{smoking_status}{factor variable}
#'   \item{family_history_cvd}{factor variable}
#'   \item{ace_inhibitor_use}{factor variable}
#'   \item{statin_use}{factor variable}
#'   \item{aspirin_use}{factor variable}
#' }
#' @keywords datasets internal
"lassocox_cardiovascular"

