# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'histopathology' so R CMD check does not flag undocumented data.
#' histopathology: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 250 rows and 38 variables:
#' \describe{
#'   \item{ID}{numeric variable}
#'   \item{Name}{character variable}
#'   \item{Sex}{character variable}
#'   \item{Age}{numeric variable}
#'   \item{Race}{character variable}
#'   \item{PreinvasiveComponent}{character variable}
#'   \item{LVI}{character variable}
#'   \item{PNI}{character variable}
#'   \item{LastFollowUpDate}{character variable}
#'   \item{Death}{character variable}
#'   \item{Group}{character variable}
#'   \item{Grade}{numeric variable}
#'   \item{TStage}{numeric variable}
#'   \item{Anti-X-intensity}{numeric variable}
#'   \item{Anti-Y-intensity}{numeric variable}
#'   \item{LymphNodeMetastasis}{character variable}
#'   \item{Valid}{character variable}
#'   \item{Smoker}{character variable}
#'   \item{Grade_Level}{character variable}
#'   \item{SurgeryDate}{character variable}
#'   \item{DeathTime}{character variable}
#'   \item{int}{character variable}
#'   \item{OverallTime}{numeric variable}
#'   \item{Outcome}{numeric variable}
#'   \item{Mortality5yr}{character variable}
#'   \item{Rater 1}{numeric variable}
#'   \item{Rater 2}{numeric variable}
#'   \item{Rater 3}{numeric variable}
#'   \item{Rater A}{numeric variable}
#'   \item{Rater B}{numeric variable}
#'   \item{New Test}{numeric variable}
#'   \item{Golden Standart}{numeric variable}
#'   \item{MeasurementA}{numeric variable}
#'   \item{MeasurementB}{numeric variable}
#'   \item{Disease Status}{character variable}
#'   \item{Measurement1}{numeric variable}
#'   \item{Measurement2}{numeric variable}
#'   \item{Outcome2}{character variable}
#' }
#' @keywords datasets internal
"histopathology"

