# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'stagemigration_large_performance' so R CMD check does not flag undocumented data.
#' stagemigration_large_performance: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 2000 rows and 9 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{age}{numeric variable}
#'   \item{sex}{factor variable}
#'   \item{cancer_type}{factor variable}
#'   \item{treatment_center}{factor variable}
#'   \item{old_stage}{factor variable}
#'   \item{new_stage}{factor variable}
#'   \item{survival_time}{numeric variable}
#'   \item{event}{integer variable}
#' }
#' @keywords datasets internal
"stagemigration_large_performance"

