# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'lassocox_breast_cancer' so R CMD check does not flag undocumented data.
#' lassocox_breast_cancer: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 250 rows and 22 variables:
#' \describe{
#'   \item{patient_id}{character variable}
#'   \item{survival_months}{numeric variable}
#'   \item{death}{factor variable}
#'   \item{age}{numeric variable}
#'   \item{menopausal_status}{factor variable}
#'   \item{tumor_size_cm}{numeric variable}
#'   \item{grade}{factor variable}
#'   \item{stage}{factor variable}
#'   \item{lymph_nodes_positive}{numeric variable}
#'   \item{lymph_nodes_examined}{numeric variable}
#'   \item{er_status}{factor variable}
#'   \item{pr_status}{factor variable}
#'   \item{her2_status}{factor variable}
#'   \item{ki67_percent}{numeric variable}
#'   \item{histology}{factor variable}
#'   \item{lvi}{factor variable}
#'   \item{margin_status}{factor variable}
#'   \item{surgery_type}{factor variable}
#'   \item{chemotherapy}{factor variable}
#'   \item{radiation}{factor variable}
#'   \item{albumin}{numeric variable}
#'   \item{hemoglobin}{numeric variable}
#' }
#' @keywords datasets internal
"lassocox_breast_cancer"

