# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'data_longitudinal' so R CMD check does not flag undocumented data.
#' data_longitudinal: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 140 rows and 3 variables:
#' \describe{
#'   \item{PatientID}{character variable}
#'   \item{Time}{integer variable}
#'   \item{Measurement}{numeric variable}
#' }
#' @keywords datasets internal
"data_longitudinal"

