# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'lassocox_lung_cancer' so R CMD check does not flag undocumented data.
#' lassocox_lung_cancer: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 200 rows and 15 variables:
#' \describe{
#'   \item{patient_id}{character variable}
#'   \item{follow_up_months}{numeric variable}
#'   \item{progression}{factor variable}
#'   \item{age}{numeric variable}
#'   \item{gender}{factor variable}
#'   \item{smoking_status}{factor variable}
#'   \item{histology}{factor variable}
#'   \item{stage}{factor variable}
#'   \item{tumor_size_cm}{numeric variable}
#'   \item{ecog_performance_status}{factor variable}
#'   \item{hemoglobin_g_dl}{numeric variable}
#'   \item{wbc_count_k_ul}{numeric variable}
#'   \item{platelet_count_k_ul}{numeric variable}
#'   \item{creatinine_mg_dl}{numeric variable}
#'   \item{treatment_type}{factor variable}
#' }
#' @keywords datasets internal
"lassocox_lung_cancer"

