# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'lassocox_small_cohort' so R CMD check does not flag undocumented data.
#' lassocox_small_cohort: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 75 rows and 10 variables:
#' \describe{
#'   \item{id}{character variable}
#'   \item{time_months}{numeric variable}
#'   \item{event_occurred}{factor variable}
#'   \item{age}{numeric variable}
#'   \item{gender}{factor variable}
#'   \item{biomarker_a}{numeric variable}
#'   \item{biomarker_b}{numeric variable}
#'   \item{biomarker_c}{numeric variable}
#'   \item{treatment_group}{factor variable}
#'   \item{severity_score}{numeric variable}
#' }
#' @keywords datasets internal
"lassocox_small_cohort"

