# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'problematic_data' so R CMD check does not flag undocumented data.
#' problematic_data: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 200 rows and 8 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{age}{numeric variable}
#'   \item{sex}{factor variable}
#'   \item{old_stage}{factor variable}
#'   \item{new_stage}{factor variable}
#'   \item{survival_time}{numeric variable}
#'   \item{event}{integer variable}
#'   \item{cancer_type}{character variable}
#' }
#' @keywords datasets internal
"problematic_data"

