# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'melanoma' so R CMD check does not flag undocumented data.
#' melanoma: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 205 rows and 7 variables:
#' \describe{
#'   \item{time}{numeric variable}
#'   \item{status}{numeric variable}
#'   \item{sex}{numeric variable}
#'   \item{age}{numeric variable}
#'   \item{year}{numeric variable}
#'   \item{thickness}{numeric variable}
#'   \item{ulcer}{numeric variable}
#' }
#' @keywords datasets internal
"melanoma"

