# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'summary_stats' so R CMD check does not flag undocumented data.
#' summary_stats: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format An object of class list of length 6.
#' @keywords datasets internal
"summary_stats"

