# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'lassocox_multicollinear' so R CMD check does not flag undocumented data.
#' lassocox_multicollinear: example dataset for the jsurvival module
#'
#' Example dataset distributed with the jsurvival jamovi module for demonstration and testing.
#'
#' @format A data frame with 180 rows and 15 variables:
#' \describe{
#'   \item{patient_id}{character variable}
#'   \item{survival_months}{numeric variable}
#'   \item{death}{factor variable}
#'   \item{age}{numeric variable}
#'   \item{sex}{factor variable}
#'   \item{ecog_ps}{factor variable}
#'   \item{comorbidity_index}{integer variable}
#'   \item{crp_mg_l}{numeric variable}
#'   \item{esr_mm_hr}{numeric variable}
#'   \item{il6_pg_ml}{numeric variable}
#'   \item{ferritin_ng_ml}{numeric variable}
#'   \item{albumin_g_dl}{numeric variable}
#'   \item{prealbumin_mg_dl}{numeric variable}
#'   \item{bmi}{numeric variable}
#'   \item{weight_loss_pct}{numeric variable}
#' }
#' @keywords datasets internal
"lassocox_multicollinear"

