
# This file is automatically generated, you probably don't want to edit this

multisurvivalOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multisurvivalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            elapsedtime = NULL,
            tint = FALSE,
            dxdate = NULL,
            fudate = NULL,
            outcome = NULL,
            outcomeLevel = NULL,
            dod = NULL,
            dooc = NULL,
            awd = NULL,
            awod = NULL,
            explanatory = NULL,
            contexpl = NULL,
            multievent = FALSE,
            analysistype = "overall",
            timetypedata = "ymd",
            timetypeoutput = "months",
            uselandmark = FALSE,
            landmark = 3,
            hr = FALSE,
            sty = "t1",
            ph_cox = FALSE,
            calculateRiskScore = FALSE,
            plotRiskGroups = FALSE,
            km = FALSE,
            endplot = 60,
            byplot = 12,
            ci95 = FALSE,
            risktable = FALSE,
            censored = FALSE,
            pplot = TRUE,
            ac = FALSE,
            adjexplanatory = NULL,
            ac_curve = FALSE,
            ac_method = "average",
            ac_summary = FALSE,
            ac_timepoints = "12, 36, 60",
            ac_compare = FALSE,
            reduced_explanatory = NULL,
            compare_models = FALSE,
            use_modelSelection = FALSE,
            modelSelection = "enter",
            selectionCriteria = "aic",
            pEntry = 0.05,
            pRemoval = 0.1,
            use_stratify = FALSE,
            stratvar = NULL, ...) {

            super$initialize(
                package="jsurvival",
                name="multisurvival",
                requiresData=TRUE,
                ...)

            private$..elapsedtime <- jmvcore::OptionVariable$new(
                "elapsedtime",
                elapsedtime,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..tint <- jmvcore::OptionBool$new(
                "tint",
                tint,
                default=FALSE)
            private$..dxdate <- jmvcore::OptionVariable$new(
                "dxdate",
                dxdate)
            private$..fudate <- jmvcore::OptionVariable$new(
                "fudate",
                fudate)
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome,
                suggested=list(
                    "ordinal",
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..outcomeLevel <- jmvcore::OptionLevel$new(
                "outcomeLevel",
                outcomeLevel,
                variable="(outcome)")
            private$..dod <- jmvcore::OptionLevel$new(
                "dod",
                dod,
                variable="(outcome)",
                allowNone=TRUE)
            private$..dooc <- jmvcore::OptionLevel$new(
                "dooc",
                dooc,
                variable="(outcome)",
                allowNone=TRUE)
            private$..awd <- jmvcore::OptionLevel$new(
                "awd",
                awd,
                variable="(outcome)",
                allowNone=TRUE)
            private$..awod <- jmvcore::OptionLevel$new(
                "awod",
                awod,
                variable="(outcome)",
                allowNone=TRUE)
            private$..explanatory <- jmvcore::OptionVariables$new(
                "explanatory",
                explanatory,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..contexpl <- jmvcore::OptionVariables$new(
                "contexpl",
                contexpl,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..multievent <- jmvcore::OptionBool$new(
                "multievent",
                multievent,
                default=FALSE)
            private$..analysistype <- jmvcore::OptionList$new(
                "analysistype",
                analysistype,
                options=list(
                    "overall",
                    "cause",
                    "compete"),
                default="overall")
            private$..outcomeredefined <- jmvcore::OptionOutput$new(
                "outcomeredefined")
            private$..timetypedata <- jmvcore::OptionList$new(
                "timetypedata",
                timetypedata,
                options=list(
                    "ymdhms",
                    "ymd",
                    "ydm",
                    "mdy",
                    "myd",
                    "dmy",
                    "dym"),
                default="ymd")
            private$..timetypeoutput <- jmvcore::OptionList$new(
                "timetypeoutput",
                timetypeoutput,
                options=list(
                    "days",
                    "weeks",
                    "months",
                    "years"),
                default="months")
            private$..uselandmark <- jmvcore::OptionBool$new(
                "uselandmark",
                uselandmark,
                default=FALSE)
            private$..landmark <- jmvcore::OptionInteger$new(
                "landmark",
                landmark,
                default=3)
            private$..calculatedtime <- jmvcore::OptionOutput$new(
                "calculatedtime")
            private$..hr <- jmvcore::OptionBool$new(
                "hr",
                hr,
                default=FALSE)
            private$..sty <- jmvcore::OptionList$new(
                "sty",
                sty,
                options=list(
                    "t1",
                    "t3"),
                default="t1")
            private$..ph_cox <- jmvcore::OptionBool$new(
                "ph_cox",
                ph_cox,
                default=FALSE)
            private$..calculateRiskScore <- jmvcore::OptionBool$new(
                "calculateRiskScore",
                calculateRiskScore,
                default=FALSE)
            private$..plotRiskGroups <- jmvcore::OptionBool$new(
                "plotRiskGroups",
                plotRiskGroups,
                default=FALSE)
            private$..addRiskScore <- jmvcore::OptionOutput$new(
                "addRiskScore")
            private$..addRiskGroup <- jmvcore::OptionOutput$new(
                "addRiskGroup")
            private$..km <- jmvcore::OptionBool$new(
                "km",
                km,
                default=FALSE)
            private$..endplot <- jmvcore::OptionInteger$new(
                "endplot",
                endplot,
                default=60)
            private$..byplot <- jmvcore::OptionInteger$new(
                "byplot",
                byplot,
                default=12)
            private$..ci95 <- jmvcore::OptionBool$new(
                "ci95",
                ci95,
                default=FALSE)
            private$..risktable <- jmvcore::OptionBool$new(
                "risktable",
                risktable,
                default=FALSE)
            private$..censored <- jmvcore::OptionBool$new(
                "censored",
                censored,
                default=FALSE)
            private$..pplot <- jmvcore::OptionBool$new(
                "pplot",
                pplot,
                default=TRUE)
            private$..ac <- jmvcore::OptionBool$new(
                "ac",
                ac,
                default=FALSE)
            private$..adjexplanatory <- jmvcore::OptionVariable$new(
                "adjexplanatory",
                adjexplanatory,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..ac_curve <- jmvcore::OptionBool$new(
                "ac_curve",
                ac_curve,
                default=FALSE)
            private$..ac_method <- jmvcore::OptionList$new(
                "ac_method",
                ac_method,
                options=list(
                    "average",
                    "conditional",
                    "single",
                    "marginal"),
                default="average")
            private$..ac_curves_output <- jmvcore::OptionOutput$new(
                "ac_curves_output")
            private$..ac_analysis_output <- jmvcore::OptionOutput$new(
                "ac_analysis_output")
            private$..ac_summary <- jmvcore::OptionBool$new(
                "ac_summary",
                ac_summary,
                default=FALSE)
            private$..ac_timepoints <- jmvcore::OptionString$new(
                "ac_timepoints",
                ac_timepoints,
                default="12, 36, 60")
            private$..ac_compare <- jmvcore::OptionBool$new(
                "ac_compare",
                ac_compare,
                default=FALSE)
            private$..reduced_explanatory <- jmvcore::OptionVariables$new(
                "reduced_explanatory",
                reduced_explanatory,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..compare_models <- jmvcore::OptionBool$new(
                "compare_models",
                compare_models,
                default=FALSE)
            private$..use_modelSelection <- jmvcore::OptionBool$new(
                "use_modelSelection",
                use_modelSelection,
                default=FALSE)
            private$..modelSelection <- jmvcore::OptionList$new(
                "modelSelection",
                modelSelection,
                options=list(
                    "enter",
                    "forward",
                    "backward",
                    "both"),
                default="enter")
            private$..selectionCriteria <- jmvcore::OptionList$new(
                "selectionCriteria",
                selectionCriteria,
                options=list(
                    "aic",
                    "lrt"),
                default="aic")
            private$..pEntry <- jmvcore::OptionNumber$new(
                "pEntry",
                pEntry,
                min=0,
                max=1,
                default=0.05)
            private$..pRemoval <- jmvcore::OptionNumber$new(
                "pRemoval",
                pRemoval,
                min=0,
                max=1,
                default=0.1)
            private$..use_stratify <- jmvcore::OptionBool$new(
                "use_stratify",
                use_stratify,
                default=FALSE)
            private$..stratvar <- jmvcore::OptionVariables$new(
                "stratvar",
                stratvar,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))

            self$.addOption(private$..elapsedtime)
            self$.addOption(private$..tint)
            self$.addOption(private$..dxdate)
            self$.addOption(private$..fudate)
            self$.addOption(private$..outcome)
            self$.addOption(private$..outcomeLevel)
            self$.addOption(private$..dod)
            self$.addOption(private$..dooc)
            self$.addOption(private$..awd)
            self$.addOption(private$..awod)
            self$.addOption(private$..explanatory)
            self$.addOption(private$..contexpl)
            self$.addOption(private$..multievent)
            self$.addOption(private$..analysistype)
            self$.addOption(private$..outcomeredefined)
            self$.addOption(private$..timetypedata)
            self$.addOption(private$..timetypeoutput)
            self$.addOption(private$..uselandmark)
            self$.addOption(private$..landmark)
            self$.addOption(private$..calculatedtime)
            self$.addOption(private$..hr)
            self$.addOption(private$..sty)
            self$.addOption(private$..ph_cox)
            self$.addOption(private$..calculateRiskScore)
            self$.addOption(private$..plotRiskGroups)
            self$.addOption(private$..addRiskScore)
            self$.addOption(private$..addRiskGroup)
            self$.addOption(private$..km)
            self$.addOption(private$..endplot)
            self$.addOption(private$..byplot)
            self$.addOption(private$..ci95)
            self$.addOption(private$..risktable)
            self$.addOption(private$..censored)
            self$.addOption(private$..pplot)
            self$.addOption(private$..ac)
            self$.addOption(private$..adjexplanatory)
            self$.addOption(private$..ac_curve)
            self$.addOption(private$..ac_method)
            self$.addOption(private$..ac_curves_output)
            self$.addOption(private$..ac_analysis_output)
            self$.addOption(private$..ac_summary)
            self$.addOption(private$..ac_timepoints)
            self$.addOption(private$..ac_compare)
            self$.addOption(private$..reduced_explanatory)
            self$.addOption(private$..compare_models)
            self$.addOption(private$..use_modelSelection)
            self$.addOption(private$..modelSelection)
            self$.addOption(private$..selectionCriteria)
            self$.addOption(private$..pEntry)
            self$.addOption(private$..pRemoval)
            self$.addOption(private$..use_stratify)
            self$.addOption(private$..stratvar)
        }),
    active = list(
        elapsedtime = function() private$..elapsedtime$value,
        tint = function() private$..tint$value,
        dxdate = function() private$..dxdate$value,
        fudate = function() private$..fudate$value,
        outcome = function() private$..outcome$value,
        outcomeLevel = function() private$..outcomeLevel$value,
        dod = function() private$..dod$value,
        dooc = function() private$..dooc$value,
        awd = function() private$..awd$value,
        awod = function() private$..awod$value,
        explanatory = function() private$..explanatory$value,
        contexpl = function() private$..contexpl$value,
        multievent = function() private$..multievent$value,
        analysistype = function() private$..analysistype$value,
        outcomeredefined = function() private$..outcomeredefined$value,
        timetypedata = function() private$..timetypedata$value,
        timetypeoutput = function() private$..timetypeoutput$value,
        uselandmark = function() private$..uselandmark$value,
        landmark = function() private$..landmark$value,
        calculatedtime = function() private$..calculatedtime$value,
        hr = function() private$..hr$value,
        sty = function() private$..sty$value,
        ph_cox = function() private$..ph_cox$value,
        calculateRiskScore = function() private$..calculateRiskScore$value,
        plotRiskGroups = function() private$..plotRiskGroups$value,
        addRiskScore = function() private$..addRiskScore$value,
        addRiskGroup = function() private$..addRiskGroup$value,
        km = function() private$..km$value,
        endplot = function() private$..endplot$value,
        byplot = function() private$..byplot$value,
        ci95 = function() private$..ci95$value,
        risktable = function() private$..risktable$value,
        censored = function() private$..censored$value,
        pplot = function() private$..pplot$value,
        ac = function() private$..ac$value,
        adjexplanatory = function() private$..adjexplanatory$value,
        ac_curve = function() private$..ac_curve$value,
        ac_method = function() private$..ac_method$value,
        ac_curves_output = function() private$..ac_curves_output$value,
        ac_analysis_output = function() private$..ac_analysis_output$value,
        ac_summary = function() private$..ac_summary$value,
        ac_timepoints = function() private$..ac_timepoints$value,
        ac_compare = function() private$..ac_compare$value,
        reduced_explanatory = function() private$..reduced_explanatory$value,
        compare_models = function() private$..compare_models$value,
        use_modelSelection = function() private$..use_modelSelection$value,
        modelSelection = function() private$..modelSelection$value,
        selectionCriteria = function() private$..selectionCriteria$value,
        pEntry = function() private$..pEntry$value,
        pRemoval = function() private$..pRemoval$value,
        use_stratify = function() private$..use_stratify$value,
        stratvar = function() private$..stratvar$value),
    private = list(
        ..elapsedtime = NA,
        ..tint = NA,
        ..dxdate = NA,
        ..fudate = NA,
        ..outcome = NA,
        ..outcomeLevel = NA,
        ..dod = NA,
        ..dooc = NA,
        ..awd = NA,
        ..awod = NA,
        ..explanatory = NA,
        ..contexpl = NA,
        ..multievent = NA,
        ..analysistype = NA,
        ..outcomeredefined = NA,
        ..timetypedata = NA,
        ..timetypeoutput = NA,
        ..uselandmark = NA,
        ..landmark = NA,
        ..calculatedtime = NA,
        ..hr = NA,
        ..sty = NA,
        ..ph_cox = NA,
        ..calculateRiskScore = NA,
        ..plotRiskGroups = NA,
        ..addRiskScore = NA,
        ..addRiskGroup = NA,
        ..km = NA,
        ..endplot = NA,
        ..byplot = NA,
        ..ci95 = NA,
        ..risktable = NA,
        ..censored = NA,
        ..pplot = NA,
        ..ac = NA,
        ..adjexplanatory = NA,
        ..ac_curve = NA,
        ..ac_method = NA,
        ..ac_curves_output = NA,
        ..ac_analysis_output = NA,
        ..ac_summary = NA,
        ..ac_timepoints = NA,
        ..ac_compare = NA,
        ..reduced_explanatory = NA,
        ..compare_models = NA,
        ..use_modelSelection = NA,
        ..modelSelection = NA,
        ..selectionCriteria = NA,
        ..pEntry = NA,
        ..pRemoval = NA,
        ..use_stratify = NA,
        ..stratvar = NA)
)

multisurvivalResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multisurvivalResults",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        text = function() private$.items[["text"]],
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]],
        plot3 = function() private$.items[["plot3"]],
        cox_ph = function() private$.items[["cox_ph"]],
        plot8 = function() private$.items[["plot8"]],
        mydataview_adj_stats = function() private$.items[["mydataview_adj_stats"]],
        mydataview_adj_summary = function() private$.items[["mydataview_adj_summary"]],
        plotKM = function() private$.items[["plotKM"]],
        riskScoreTable = function() private$.items[["riskScoreTable"]],
        riskScoreMetrics = function() private$.items[["riskScoreMetrics"]],
        riskGroupPlot = function() private$.items[["riskGroupPlot"]],
        calculatedtime = function() private$.items[["calculatedtime"]],
        outcomeredefined = function() private$.items[["outcomeredefined"]],
        addRiskScore = function() private$.items[["addRiskScore"]],
        addRiskGroup = function() private$.items[["addRiskGroup"]],
        plot_adj = function() private$.items[["plot_adj"]],
        mydataview_curve_data = function() private$.items[["mydataview_curve_data"]],
        adjustedSummaryStats = function() private$.items[["adjustedSummaryStats"]],
        adjustedSummaryTable = function() private$.items[["adjustedSummaryTable"]],
        adjustedComparison = function() private$.items[["adjustedComparison"]],
        ac_summary_table = function() private$.items[["ac_summary_table"]],
        ac_landmark_table = function() private$.items[["ac_landmark_table"]],
        ac_text_summary = function() private$.items[["ac_text_summary"]],
        model_comparison = function() private$.items[["model_comparison"]],
        reduced_model_metrics = function() private$.items[["reduced_model_metrics"]],
        text_model_selection = function() private$.items[["text_model_selection"]],
        text2_model_selection = function() private$.items[["text2_model_selection"]],
        selectionSteps = function() private$.items[["selectionSteps"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multivariable Survival Analysis",
                refs=list(
                    "multivariable",
                    "survivaltutorial",
                    "survivalrwnahhas",
                    "ClinicoPathJamoviModule"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do",
                clearWith=list(
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent")))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Multivariable Survival",
                refs="finalfit",
                clearWith=list(
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent")))
            self$add(jmvcore::Html$new(
                options=options,
                name="text2",
                title="",
                refs="finalfit",
                clearWith=list(
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Hazards Regression Plot",
                width=600,
                height=450,
                renderFun=".plot",
                requiresData=TRUE,
                visible="(hr && sty:t1)",
                refs="finalfit",
                clearWith=list(
                    "hr",
                    "sty",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Hazards Regression Plot",
                width=800,
                height=600,
                renderFun=".plot3",
                requiresData=TRUE,
                visible="(hr && sty:t3)",
                refs="survminer",
                clearWith=list(
                    "hr",
                    "sty",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cox_ph",
                title="Proportional Hazards Assumption",
                visible="(ph_cox)",
                clearWith=list(
                    "explanatory",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "contexpl")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot8",
                title="Proportional Hazards Assumption",
                width=600,
                height=450,
                renderFun=".plot8",
                visible="(ph_cox)",
                requiresData=TRUE,
                clearWith=list(
                    "ph_cox",
                    "endplot",
                    "byplot",
                    "explanatory",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "contexpl")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mydataview_adj_stats",
                title="mydataview"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mydataview_adj_summary",
                title="mydataview"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotKM",
                title="Kaplan-Meier",
                width=600,
                height=450,
                renderFun=".plotKM",
                requiresData=TRUE,
                visible="(km)",
                refs="finalfit",
                clearWith=list(
                    "km",
                    "endplot",
                    "byplot",
                    "ci95",
                    "risktable",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "adjexplanatory",
                    "pplot",
                    "censored")))
            self$add(jmvcore::Table$new(
                options=options,
                name="riskScoreTable",
                title="Risk Score Summary",
                visible="(calculateRiskScore)",
                rows=0,
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Risk Group", 
                        `type`="text"),
                    list(
                        `name`="n_patients", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="percent", 
                        `title`="Percent", 
                        `type`="number"),
                    list(
                        `name`="median_score", 
                        `title`="Median Score", 
                        `type`="number"),
                    list(
                        `name`="events", 
                        `title`="Events", 
                        `type`="integer")),
                clearWith=list(
                    "calculateRiskScore",
                    "outcome",
                    "outcomeLevel",
                    "explanatory",
                    "contexpl")))
            self$add(jmvcore::Html$new(
                options=options,
                name="riskScoreMetrics",
                title="Risk Score Model Metrics",
                visible="(calculateRiskScore)",
                clearWith=list(
                    "calculateRiskScore",
                    "outcome",
                    "outcomeLevel",
                    "explanatory",
                    "contexpl")))
            self$add(jmvcore::Image$new(
                options=options,
                name="riskGroupPlot",
                title="Risk Group Survival Plot",
                width=600,
                height=450,
                renderFun=".plotRiskGroups",
                requiresData=TRUE,
                visible="(plotRiskGroups)"))
            self$add(jmvcore::Output$new(
                options=options,
                name="calculatedtime",
                title="Add Calculated Time to Data",
                varTitle="`Calculated Time in Multivariable Survival Function - from ${ dxdate } to { fudate }`",
                varDescription="Calculated Time from given Dates in Multivariable Survival Analysis",
                clearWith=list(
                    "tint",
                    "dxdate",
                    "fudate")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outcomeredefined",
                title="Add Redefined Outcome to Data",
                varTitle="`Redefined Outcome in Multivariable Survival Function - from ${ outcome } for analysis { analysistype }`",
                varDescription="Redefined Outcome from Outcome based on Analysis Type in Multivariable Survival Analysis",
                clearWith=list(
                    "outcome",
                    "analysistype",
                    "multievent")))
            self$add(jmvcore::Output$new(
                options=options,
                name="addRiskScore",
                title="Add Calculated Risk Score to Data",
                varTitle="`Calculated Risk Score in Multivariable Survival Function`",
                varDescription="Calculated Risk Score Based on Model",
                clearWith=list(
                    "addRiskScore",
                    "calculateRiskScore",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "addRiskGroup")))
            self$add(jmvcore::Output$new(
                options=options,
                name="addRiskGroup",
                title="Add Calculated Risk Group to Data",
                varTitle="`Calculated Risk Group in Multivariable Survival Function`",
                varDescription="Calculated Risk Group Based on Model",
                clearWith=list(
                    "addRiskScore",
                    "calculateRiskScore",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "addRiskGroup")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot_adj",
                title="Adjusted Survival Plot",
                width=600,
                height=450,
                renderFun=".plot_adj",
                visible="(ac && ac_curve)",
                requiresData=TRUE,
                refs="survminer",
                clearWith=list(
                    "ac",
                    "adjexplanatory",
                    "ci95",
                    "risktable",
                    "ac_method")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mydataview_curve_data",
                title="mydataview_curve_data",
                visible="(ac)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="adjustedSummaryStats",
                title="adjustedSummaryStats"))
            self$add(jmvcore::Table$new(
                options=options,
                name="adjustedSummaryTable",
                title="Adjusted Survival Summary",
                visible="(ac_summary)",
                rows=0,
                columns=list(
                    list(
                        `name`="Level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="Timepoint", 
                        `title`="Time", 
                        `type`="integer"),
                    list(
                        `name`="Survival", 
                        `title`="Adjusted Survival", 
                        `type`="number", 
                        `format`="proportion"),
                    list(
                        `name`="SE", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="CI_Lower", 
                        `title`="95% CI Lower", 
                        `type`="number", 
                        `format`="proportion"),
                    list(
                        `name`="CI_Upper", 
                        `title`="95% CI Upper", 
                        `type`="number", 
                        `format`="proportion")),
                clearWith=list(
                    "ac_summary",
                    "ac_timepoints",
                    "ac_method",
                    "adjexplanatory")))
            self$add(jmvcore::Html$new(
                options=options,
                name="adjustedComparison",
                title="Statistical Comparison of Adjusted Curves",
                visible="(ac_compare)",
                clearWith=list(
                    "ac_compare",
                    "ac_method",
                    "adjexplanatory")))
            self$add(jmvcore::Table$new(
                options=options,
                name="ac_summary_table",
                title="Adjusted Survival Analysis",
                rows=0,
                visible="(ac_summary)",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="median_time", 
                        `title`="Median Survival", 
                        `type`="number"),
                    list(
                        `name`="median_surv", 
                        `title`="Median Survival Rate", 
                        `type`="number"),
                    list(
                        `name`="hr", 
                        `title`="Hazard Ratio", 
                        `type`="number"),
                    list(
                        `name`="hr_ci_lower", 
                        `title`="HR CI Lower", 
                        `type`="number"),
                    list(
                        `name`="hr_ci_upper", 
                        `title`="HR CI Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ac_landmark_table",
                title="Landmark Analysis",
                rows=0,
                visible="(ac_summary)",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="timepoint", 
                        `title`="Time", 
                        `type`="integer"),
                    list(
                        `name`="survival_rate", 
                        `title`="Survival Rate", 
                        `type`="number"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="ac_text_summary",
                title="Analysis Summary",
                visible="(ac_summary)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="model_comparison",
                title="Model Comparison",
                visible="(compare_models)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="reduced_model_metrics",
                title="Reduced Model Performance Metrics",
                visible="(compare_models)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text_model_selection",
                title="Multivariable Survival with Model Selection",
                refs="finalfit",
                visible="(use_modelSelection)",
                clearWith=list(
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "modelSelection",
                    "selectionCriteria",
                    "pEntry",
                    "pRemoval")))
            self$add(jmvcore::Html$new(
                options=options,
                name="text2_model_selection",
                title="",
                refs="finalfit",
                visible="(use_modelSelection)",
                clearWith=list(
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "modelSelection",
                    "selectionCriteria",
                    "pEntry",
                    "pRemoval")))
            self$add(jmvcore::Table$new(
                options=options,
                name="selectionSteps",
                title="Model Selection Steps",
                visible="(use_modelSelection)",
                columns=list(
                    list(
                        `name`="step", 
                        `title`="Step", 
                        `type`="integer"),
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="action", 
                        `title`="Action", 
                        `type`="text"),
                    list(
                        `name`="criterion", 
                        `title`="Criterion Value", 
                        `type`="number"),
                    list(
                        `name`="pvalue", 
                        `title`="P-value", 
                        `type`="number")),
                refs="finalfit",
                clearWith=list(
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "modelSelection",
                    "selectionCriteria",
                    "pEntry",
                    "pRemoval")))}))

multisurvivalBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multisurvivalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jsurvival",
                name = "multisurvival",
                version = c(1,0,0),
                options = options,
                results = multisurvivalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Multivariable Survival Analysis
#'
#' Function for Multivariable Survival Analysis using Cox-regression.
#'
#' @examples
#' \donttest{
#' # example will be added
#'}
#' @param data The dataset to be analyzed, provided as a data frame. Must
#'   contain the variables specified in the options below.
#' @param elapsedtime The numeric variable representing follow-up time until
#'   the event or last observation. If \code{tint} = false, this should be a
#'   pre-calculated numeric time variable. If \code{tint} = true, \code{dxdate}
#'   and \code{fudate} will be used to calculate this time.
#' @param tint If true, survival time will be calculated from \code{dxdate}
#'   and \code{fudate}. If false, \code{elapsedtime} should be provided as a
#'   pre-calculated numeric variable.
#' @param dxdate Date of diagnosis. Required if \code{tint} = true. Must match
#'   the format specified in \code{timetypedata}.
#' @param fudate Follow-up date or date of last observation. Required if
#'   \code{tint} = true. Must match the format specified in \code{timetypedata}.
#' @param outcome The outcome variable. Typically indicates event status
#'   (e.g., death, recurrence). For survival analysis, this may be a factor or
#'   numeric event indicator.
#' @param outcomeLevel The level of \code{outcome} considered as the event.
#'   For example, if \code{outcome} is a factor, specify which level indicates
#'   the event occurrence.
#' @param dod The level of \code{outcome} corresponding to death due to
#'   disease, if applicable.
#' @param dooc The level of \code{outcome} corresponding to death due to other
#'   causes, if applicable.
#' @param awd The level of \code{outcome} corresponding to alive with disease,
#'   if applicable.
#' @param awod The level of \code{outcome} corresponding to alive without
#'   disease, if applicable.
#' @param explanatory Categorical explanatory (predictor) variables included
#'   in the Cox model.
#' @param contexpl Continuous explanatory (predictor) variables included in
#'   the Cox model.
#' @param multievent If true, multiple event levels will be considered for
#'   competing risks analysis. Requires specifying \code{dod}, \code{dooc}, etc.
#' @param analysistype Type of survival analysis: - overall: All-cause
#'   survival - cause: Cause-specific survival - compete: Competing risks
#'   analysis
#' @param timetypedata Specifies the format of the date variables in the input
#'   data. This is critical if \code{tint = true}, as \code{dxdate} and
#'   \code{fudate} will be parsed according to this format to calculate survival
#'   time. For example, if your data files record dates as "YYYY-MM-DD", select
#'   \code{ymd}.
#' @param timetypeoutput The units in which survival time is reported in the
#'   output. Choose from days, weeks, months, or years.
#' @param uselandmark If true, applies a landmark analysis starting at a
#'   specified time point.
#' @param landmark The time point (in the units defined by
#'   \code{timetypeoutput}) at which to start landmark analyses. Only used if
#'   \code{uselandmark} = true.
#' @param hr If true, generates a plot of hazard ratios for each explanatory
#'   variable in the Cox model.
#' @param sty The style of the hazard ratio (forest) plot. "finalfit" or
#'   "survminer forestplot".
#' @param ph_cox If true, tests the proportional hazards assumption for the
#'   Cox model. Use if you suspect violations of the PH assumption.
#' @param calculateRiskScore If true, calculates a risk score from the Cox
#'   model coefficients for each individual.
#' @param plotRiskGroups If true, stratifies individuals into risk groups
#'   based on their calculated risk scores and plots their survival curves.
#' @param km If true, produces a Kaplan-Meier survival plot. Useful for
#'   visualization of survival functions without covariate adjustment.
#' @param endplot The maximum follow-up time (in units defined by
#'   \code{timetypeoutput}) to display on survival plots.
#' @param byplot The interval (in units defined by \code{timetypeoutput}) at
#'   which time points or labels are shown on plots.
#' @param ci95 If true, displays 95\% confidence intervals around the survival
#'   estimates on plots.
#' @param risktable If true, displays the number of subjects at risk at each
#'   time point below the survival plot.
#' @param censored If true, marks censored observations (e.g., using tick
#'   marks) on the survival plot.
#' @param pplot If true, displays the p-value from the survival comparison
#'   test on the survival plot.
#' @param ac If true, computes and displays adjusted survival curves based on
#'   specified variables.
#' @param adjexplanatory The categorical variable used to stratify and adjust
#'   the survival curve. Only relevant if \code{ac} = true.
#' @param ac_curve .
#' @param ac_method The method used to compute adjusted survival curves. This
#'   affects how covariates are handled when producing adjusted survival
#'   estimates.
#' @param ac_summary If true, calculates and displays summary statistics
#'   (e.g., survival probabilities at specific timepoints) for the adjusted
#'   survival curves.
#' @param ac_timepoints Comma-separated time points (in \code{timetypeoutput}
#'   units) at which summary statistics for adjusted curves are calculated. For
#'   example: '12, 36, 60' for 12, 36, and 60 months.
#' @param ac_compare If true, performs a statistical comparison (e.g.,
#'   log-rank test) between adjusted survival curves.
#' @param reduced_explanatory Variables to include in a reduced model for
#'   comparison. This can be used to test whether excluding some variables
#'   affects model fit.
#' @param compare_models If true, compares the full model against the reduced
#'   model to assess the impact of removing certain explanatory variables.
#' @param use_modelSelection If true, applies a variable selection procedure
#'   to find the best-fitting model based on criteria like AIC or likelihood
#'   ratio tests.
#' @param modelSelection The method used to select variables: - enter:
#'   Includes all variables (no selection) - forward: Adds variables one at a
#'   time if they improve the model - backward: Removes variables that do not
#'   significantly contribute - both: Combination of forward and backward steps
#' @param selectionCriteria The criterion used for adding or removing
#'   variables in model selection: - aic: Balances model fit and complexity -
#'   lrt: Uses likelihood ratio tests to decide inclusion/removal
#' @param pEntry Significance level at which a variable enters the model
#'   during forward or stepwise selection.
#' @param pRemoval Significance level at which a variable is removed from the
#'   model during backward or stepwise selection.
#' @param use_stratify If true, uses stratification to handle variables that
#'   violate the proportional hazards assumption. Stratification creates
#'   separate baseline hazard functions for different groups.
#' @param stratvar Variables used for stratification. When proportional
#'   hazards are not met, stratification can adjust the model to better fit the
#'   data by allowing different baseline hazards.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cox_ph} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot8} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mydataview_adj_stats} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$mydataview_adj_summary} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plotKM} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$riskScoreTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$riskScoreMetrics} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$riskGroupPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$calculatedtime} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outcomeredefined} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$addRiskScore} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$addRiskGroup} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot_adj} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mydataview_curve_data} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$adjustedSummaryStats} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$adjustedSummaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$adjustedComparison} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ac_summary_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ac_landmark_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ac_text_summary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$model_comparison} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reduced_model_metrics} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text_model_selection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text2_model_selection} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$selectionSteps} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$riskScoreTable$asDF}
#'
#' \code{as.data.frame(results$riskScoreTable)}
#'
#' @export
multisurvival <- function(
    data,
    elapsedtime,
    tint = FALSE,
    dxdate,
    fudate,
    outcome,
    outcomeLevel,
    dod,
    dooc,
    awd,
    awod,
    explanatory,
    contexpl,
    multievent = FALSE,
    analysistype = "overall",
    timetypedata = "ymd",
    timetypeoutput = "months",
    uselandmark = FALSE,
    landmark = 3,
    hr = FALSE,
    sty = "t1",
    ph_cox = FALSE,
    calculateRiskScore = FALSE,
    plotRiskGroups = FALSE,
    km = FALSE,
    endplot = 60,
    byplot = 12,
    ci95 = FALSE,
    risktable = FALSE,
    censored = FALSE,
    pplot = TRUE,
    ac = FALSE,
    adjexplanatory,
    ac_curve = FALSE,
    ac_method = "average",
    ac_summary = FALSE,
    ac_timepoints = "12, 36, 60",
    ac_compare = FALSE,
    reduced_explanatory,
    compare_models = FALSE,
    use_modelSelection = FALSE,
    modelSelection = "enter",
    selectionCriteria = "aic",
    pEntry = 0.05,
    pRemoval = 0.1,
    use_stratify = FALSE,
    stratvar) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("multisurvival requires jmvcore to be installed (restart may be required)")

    if ( ! missing(elapsedtime)) elapsedtime <- jmvcore::resolveQuo(jmvcore::enquo(elapsedtime))
    if ( ! missing(dxdate)) dxdate <- jmvcore::resolveQuo(jmvcore::enquo(dxdate))
    if ( ! missing(fudate)) fudate <- jmvcore::resolveQuo(jmvcore::enquo(fudate))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(explanatory)) explanatory <- jmvcore::resolveQuo(jmvcore::enquo(explanatory))
    if ( ! missing(contexpl)) contexpl <- jmvcore::resolveQuo(jmvcore::enquo(contexpl))
    if ( ! missing(adjexplanatory)) adjexplanatory <- jmvcore::resolveQuo(jmvcore::enquo(adjexplanatory))
    if ( ! missing(reduced_explanatory)) reduced_explanatory <- jmvcore::resolveQuo(jmvcore::enquo(reduced_explanatory))
    if ( ! missing(stratvar)) stratvar <- jmvcore::resolveQuo(jmvcore::enquo(stratvar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(elapsedtime), elapsedtime, NULL),
            `if`( ! missing(dxdate), dxdate, NULL),
            `if`( ! missing(fudate), fudate, NULL),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(explanatory), explanatory, NULL),
            `if`( ! missing(contexpl), contexpl, NULL),
            `if`( ! missing(adjexplanatory), adjexplanatory, NULL),
            `if`( ! missing(reduced_explanatory), reduced_explanatory, NULL),
            `if`( ! missing(stratvar), stratvar, NULL))

    for (v in explanatory) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in adjexplanatory) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in reduced_explanatory) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in stratvar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- multisurvivalOptions$new(
        elapsedtime = elapsedtime,
        tint = tint,
        dxdate = dxdate,
        fudate = fudate,
        outcome = outcome,
        outcomeLevel = outcomeLevel,
        dod = dod,
        dooc = dooc,
        awd = awd,
        awod = awod,
        explanatory = explanatory,
        contexpl = contexpl,
        multievent = multievent,
        analysistype = analysistype,
        timetypedata = timetypedata,
        timetypeoutput = timetypeoutput,
        uselandmark = uselandmark,
        landmark = landmark,
        hr = hr,
        sty = sty,
        ph_cox = ph_cox,
        calculateRiskScore = calculateRiskScore,
        plotRiskGroups = plotRiskGroups,
        km = km,
        endplot = endplot,
        byplot = byplot,
        ci95 = ci95,
        risktable = risktable,
        censored = censored,
        pplot = pplot,
        ac = ac,
        adjexplanatory = adjexplanatory,
        ac_curve = ac_curve,
        ac_method = ac_method,
        ac_summary = ac_summary,
        ac_timepoints = ac_timepoints,
        ac_compare = ac_compare,
        reduced_explanatory = reduced_explanatory,
        compare_models = compare_models,
        use_modelSelection = use_modelSelection,
        modelSelection = modelSelection,
        selectionCriteria = selectionCriteria,
        pEntry = pEntry,
        pRemoval = pRemoval,
        use_stratify = use_stratify,
        stratvar = stratvar)

    analysis <- multisurvivalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

