
# This file is automatically generated, you probably don't want to edit this

multisurvivalOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "multisurvivalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            elapsedtime = NULL,
            tint = FALSE,
            dxdate = NULL,
            fudate = NULL,
            explanatory = NULL,
            outcome = NULL,
            outcomeLevel = NULL,
            dod = NULL,
            dooc = NULL,
            awd = NULL,
            awod = NULL,
            multievent = FALSE,
            analysistype = "overall",
            timetypedata = "ymd",
            timetypeoutput = "months",
            hr = FALSE,
            sty = "t1",
            km = FALSE,
            ac = FALSE,
            adjexplanatory = NULL, ...) {

            super$initialize(
                package='jsurvival',
                name='multisurvival',
                requiresData=TRUE,
                ...)

            private$..elapsedtime <- jmvcore::OptionVariable$new(
                "elapsedtime",
                elapsedtime,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..tint <- jmvcore::OptionBool$new(
                "tint",
                tint,
                default=FALSE)
            private$..dxdate <- jmvcore::OptionVariable$new(
                "dxdate",
                dxdate)
            private$..fudate <- jmvcore::OptionVariable$new(
                "fudate",
                fudate)
            private$..explanatory <- jmvcore::OptionVariables$new(
                "explanatory",
                explanatory,
                suggested=list(
                    "ordinal",
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome,
                suggested=list(
                    "ordinal",
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..outcomeLevel <- jmvcore::OptionLevel$new(
                "outcomeLevel",
                outcomeLevel,
                variable="(outcome)")
            private$..dod <- jmvcore::OptionLevel$new(
                "dod",
                dod,
                variable="(outcome)",
                allowNone=TRUE)
            private$..dooc <- jmvcore::OptionLevel$new(
                "dooc",
                dooc,
                variable="(outcome)",
                allowNone=TRUE)
            private$..awd <- jmvcore::OptionLevel$new(
                "awd",
                awd,
                variable="(outcome)",
                allowNone=TRUE)
            private$..awod <- jmvcore::OptionLevel$new(
                "awod",
                awod,
                variable="(outcome)",
                allowNone=TRUE)
            private$..multievent <- jmvcore::OptionBool$new(
                "multievent",
                multievent,
                default=FALSE)
            private$..analysistype <- jmvcore::OptionList$new(
                "analysistype",
                analysistype,
                options=list(
                    "overall",
                    "cause"),
                default="overall")
            private$..timetypedata <- jmvcore::OptionList$new(
                "timetypedata",
                timetypedata,
                options=list(
                    "ymdhms",
                    "ymd",
                    "ydm",
                    "mdy",
                    "myd",
                    "dmy",
                    "dym"),
                default="ymd")
            private$..timetypeoutput <- jmvcore::OptionList$new(
                "timetypeoutput",
                timetypeoutput,
                options=list(
                    "days",
                    "weeks",
                    "months",
                    "years"),
                default="months")
            private$..hr <- jmvcore::OptionBool$new(
                "hr",
                hr,
                default=FALSE)
            private$..sty <- jmvcore::OptionList$new(
                "sty",
                sty,
                options=list(
                    "t1",
                    "t3"),
                default="t1")
            private$..km <- jmvcore::OptionBool$new(
                "km",
                km,
                default=FALSE)
            private$..ac <- jmvcore::OptionBool$new(
                "ac",
                ac,
                default=FALSE)
            private$..adjexplanatory <- jmvcore::OptionVariable$new(
                "adjexplanatory",
                adjexplanatory)

            self$.addOption(private$..elapsedtime)
            self$.addOption(private$..tint)
            self$.addOption(private$..dxdate)
            self$.addOption(private$..fudate)
            self$.addOption(private$..explanatory)
            self$.addOption(private$..outcome)
            self$.addOption(private$..outcomeLevel)
            self$.addOption(private$..dod)
            self$.addOption(private$..dooc)
            self$.addOption(private$..awd)
            self$.addOption(private$..awod)
            self$.addOption(private$..multievent)
            self$.addOption(private$..analysistype)
            self$.addOption(private$..timetypedata)
            self$.addOption(private$..timetypeoutput)
            self$.addOption(private$..hr)
            self$.addOption(private$..sty)
            self$.addOption(private$..km)
            self$.addOption(private$..ac)
            self$.addOption(private$..adjexplanatory)
        }),
    active = list(
        elapsedtime = function() private$..elapsedtime$value,
        tint = function() private$..tint$value,
        dxdate = function() private$..dxdate$value,
        fudate = function() private$..fudate$value,
        explanatory = function() private$..explanatory$value,
        outcome = function() private$..outcome$value,
        outcomeLevel = function() private$..outcomeLevel$value,
        dod = function() private$..dod$value,
        dooc = function() private$..dooc$value,
        awd = function() private$..awd$value,
        awod = function() private$..awod$value,
        multievent = function() private$..multievent$value,
        analysistype = function() private$..analysistype$value,
        timetypedata = function() private$..timetypedata$value,
        timetypeoutput = function() private$..timetypeoutput$value,
        hr = function() private$..hr$value,
        sty = function() private$..sty$value,
        km = function() private$..km$value,
        ac = function() private$..ac$value,
        adjexplanatory = function() private$..adjexplanatory$value),
    private = list(
        ..elapsedtime = NA,
        ..tint = NA,
        ..dxdate = NA,
        ..fudate = NA,
        ..explanatory = NA,
        ..outcome = NA,
        ..outcomeLevel = NA,
        ..dod = NA,
        ..dooc = NA,
        ..awd = NA,
        ..awod = NA,
        ..multievent = NA,
        ..analysistype = NA,
        ..timetypedata = NA,
        ..timetypeoutput = NA,
        ..hr = NA,
        ..sty = NA,
        ..km = NA,
        ..ac = NA,
        ..adjexplanatory = NA)
)

multisurvivalResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        mydataview = function() private$.items[["mydataview"]],
        text = function() private$.items[["text"]],
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]],
        plot3 = function() private$.items[["plot3"]],
        plotKM = function() private$.items[["plotKM"]],
        plot7 = function() private$.items[["plot7"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multivariate Survival Analysis",
                clearWith=list(
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "fudate",
                    "dxdate"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mydataview",
                title="mydataview"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Multivariate Survival",
                refs="finalfit"))
            self$add(jmvcore::Html$new(
                options=options,
                name="text2",
                title="",
                refs="finalfit"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Hazards Regression Plot",
                width=600,
                height=450,
                renderFun=".plot",
                requiresData=TRUE,
                visible="(hr && sty:t1)",
                refs="finalfit"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Hazards Regression Plot",
                width=800,
                height=600,
                renderFun=".plot3",
                requiresData=TRUE,
                visible="(hr && sty:t3)",
                refs="survminer"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotKM",
                title="Kaplan-Meier",
                width=600,
                height=450,
                renderFun=".plot",
                requiresData=TRUE,
                visible="(km)",
                refs="finalfit"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot7",
                title="`Adjusted Survival Curve - ${adjexplanatory}`",
                width=800,
                height=600,
                renderFun=".plot7",
                requiresData=TRUE,
                visible="(ac)",
                refs="survminer"))}))

multisurvivalBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "multisurvivalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jsurvival',
                name = 'multisurvival',
                version = c(1,0,0),
                options = options,
                results = multisurvivalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Multivariate Survival Analysis
#'
#' Function for Multivariate Survival Analysis using Cox-regression.
#'
#' @examples
#' \dontrun{
#' # example will be added
#'}
#' @param data The data as a data frame.
#' @param elapsedtime .
#' @param tint .
#' @param dxdate .
#' @param fudate .
#' @param explanatory .
#' @param outcome .
#' @param outcomeLevel .
#' @param dod .
#' @param dooc .
#' @param awd .
#' @param awod .
#' @param multievent .
#' @param analysistype .
#' @param timetypedata select the time type in data
#' @param timetypeoutput select the time type in output
#' @param hr .
#' @param sty .
#' @param km .
#' @param ac .
#' @param adjexplanatory .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$mydataview} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotKM} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot7} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
multisurvival <- function(
    data,
    elapsedtime,
    tint = FALSE,
    dxdate,
    fudate,
    explanatory,
    outcome,
    outcomeLevel,
    dod,
    dooc,
    awd,
    awod,
    multievent = FALSE,
    analysistype = "overall",
    timetypedata = "ymd",
    timetypeoutput = "months",
    hr = FALSE,
    sty = "t1",
    km = FALSE,
    ac = FALSE,
    adjexplanatory) {

    if ( ! requireNamespace('jmvcore'))
        stop('multisurvival requires jmvcore to be installed (restart may be required)')

    if ( ! missing(elapsedtime)) elapsedtime <- jmvcore::resolveQuo(jmvcore::enquo(elapsedtime))
    if ( ! missing(dxdate)) dxdate <- jmvcore::resolveQuo(jmvcore::enquo(dxdate))
    if ( ! missing(fudate)) fudate <- jmvcore::resolveQuo(jmvcore::enquo(fudate))
    if ( ! missing(explanatory)) explanatory <- jmvcore::resolveQuo(jmvcore::enquo(explanatory))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(adjexplanatory)) adjexplanatory <- jmvcore::resolveQuo(jmvcore::enquo(adjexplanatory))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(elapsedtime), elapsedtime, NULL),
            `if`( ! missing(dxdate), dxdate, NULL),
            `if`( ! missing(fudate), fudate, NULL),
            `if`( ! missing(explanatory), explanatory, NULL),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(adjexplanatory), adjexplanatory, NULL))


    options <- multisurvivalOptions$new(
        elapsedtime = elapsedtime,
        tint = tint,
        dxdate = dxdate,
        fudate = fudate,
        explanatory = explanatory,
        outcome = outcome,
        outcomeLevel = outcomeLevel,
        dod = dod,
        dooc = dooc,
        awd = awd,
        awod = awod,
        multievent = multievent,
        analysistype = analysistype,
        timetypedata = timetypedata,
        timetypeoutput = timetypeoutput,
        hr = hr,
        sty = sty,
        km = km,
        ac = ac,
        adjexplanatory = adjexplanatory)

    analysis <- multisurvivalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
