
# This file is automatically generated, you probably don't want to edit this

multisurvivalOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multisurvivalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            elapsedtime = NULL,
            tint = FALSE,
            dxdate = NULL,
            fudate = NULL,
            outcome = NULL,
            outcomeLevel = NULL,
            dod = NULL,
            dooc = NULL,
            awd = NULL,
            awod = NULL,
            explanatory = NULL,
            contexpl = NULL,
            multievent = FALSE,
            analysistype = "overall",
            timetypedata = "ymd",
            timetypeoutput = "months",
            uselandmark = FALSE,
            landmark = 3,
            hr = FALSE,
            sty = "t1",
            ph_cox = FALSE,
            calculateRiskScore = FALSE,
            ac = FALSE,
            adjexplanatory = NULL,
            km = FALSE,
            endplot = 60,
            byplot = 12,
            ci95 = FALSE,
            risktable = FALSE,
            censored = FALSE,
            pplot = TRUE,
            ac_method = "average",
            ac_summary = FALSE,
            ac_timepoints = "12, 36, 60",
            ac_compare = FALSE, ...) {

            super$initialize(
                package="jsurvival",
                name="multisurvival",
                requiresData=TRUE,
                ...)

            private$..elapsedtime <- jmvcore::OptionVariable$new(
                "elapsedtime",
                elapsedtime,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..tint <- jmvcore::OptionBool$new(
                "tint",
                tint,
                default=FALSE)
            private$..dxdate <- jmvcore::OptionVariable$new(
                "dxdate",
                dxdate)
            private$..fudate <- jmvcore::OptionVariable$new(
                "fudate",
                fudate)
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome,
                suggested=list(
                    "ordinal",
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..outcomeLevel <- jmvcore::OptionLevel$new(
                "outcomeLevel",
                outcomeLevel,
                variable="(outcome)")
            private$..dod <- jmvcore::OptionLevel$new(
                "dod",
                dod,
                variable="(outcome)",
                allowNone=TRUE)
            private$..dooc <- jmvcore::OptionLevel$new(
                "dooc",
                dooc,
                variable="(outcome)",
                allowNone=TRUE)
            private$..awd <- jmvcore::OptionLevel$new(
                "awd",
                awd,
                variable="(outcome)",
                allowNone=TRUE)
            private$..awod <- jmvcore::OptionLevel$new(
                "awod",
                awod,
                variable="(outcome)",
                allowNone=TRUE)
            private$..explanatory <- jmvcore::OptionVariables$new(
                "explanatory",
                explanatory,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..contexpl <- jmvcore::OptionVariables$new(
                "contexpl",
                contexpl,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..multievent <- jmvcore::OptionBool$new(
                "multievent",
                multievent,
                default=FALSE)
            private$..analysistype <- jmvcore::OptionList$new(
                "analysistype",
                analysistype,
                options=list(
                    "overall",
                    "cause",
                    "compete"),
                default="overall")
            private$..outcomeredefined <- jmvcore::OptionOutput$new(
                "outcomeredefined")
            private$..timetypedata <- jmvcore::OptionList$new(
                "timetypedata",
                timetypedata,
                options=list(
                    "ymdhms",
                    "ymd",
                    "ydm",
                    "mdy",
                    "myd",
                    "dmy",
                    "dym"),
                default="ymd")
            private$..timetypeoutput <- jmvcore::OptionList$new(
                "timetypeoutput",
                timetypeoutput,
                options=list(
                    "days",
                    "weeks",
                    "months",
                    "years"),
                default="months")
            private$..uselandmark <- jmvcore::OptionBool$new(
                "uselandmark",
                uselandmark,
                default=FALSE)
            private$..landmark <- jmvcore::OptionInteger$new(
                "landmark",
                landmark,
                default=3)
            private$..calculatedtime <- jmvcore::OptionOutput$new(
                "calculatedtime")
            private$..hr <- jmvcore::OptionBool$new(
                "hr",
                hr,
                default=FALSE)
            private$..sty <- jmvcore::OptionList$new(
                "sty",
                sty,
                options=list(
                    "t1",
                    "t3"),
                default="t1")
            private$..ph_cox <- jmvcore::OptionBool$new(
                "ph_cox",
                ph_cox,
                default=FALSE)
            private$..calculateRiskScore <- jmvcore::OptionBool$new(
                "calculateRiskScore",
                calculateRiskScore,
                default=FALSE)
            private$..addRiskScore <- jmvcore::OptionOutput$new(
                "addRiskScore")
            private$..addRiskGroup <- jmvcore::OptionOutput$new(
                "addRiskGroup")
            private$..ac <- jmvcore::OptionBool$new(
                "ac",
                ac,
                default=FALSE)
            private$..adjexplanatory <- jmvcore::OptionVariable$new(
                "adjexplanatory",
                adjexplanatory,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..km <- jmvcore::OptionBool$new(
                "km",
                km,
                default=FALSE)
            private$..endplot <- jmvcore::OptionInteger$new(
                "endplot",
                endplot,
                default=60)
            private$..byplot <- jmvcore::OptionInteger$new(
                "byplot",
                byplot,
                default=12)
            private$..ci95 <- jmvcore::OptionBool$new(
                "ci95",
                ci95,
                default=FALSE)
            private$..risktable <- jmvcore::OptionBool$new(
                "risktable",
                risktable,
                default=FALSE)
            private$..censored <- jmvcore::OptionBool$new(
                "censored",
                censored,
                default=FALSE)
            private$..pplot <- jmvcore::OptionBool$new(
                "pplot",
                pplot,
                default=TRUE)
            private$..ac_method <- jmvcore::OptionList$new(
                "ac_method",
                ac_method,
                options=list(
                    "average",
                    "conditional_mean",
                    "direct",
                    "marginal"),
                default="average")
            private$..ac_summary <- jmvcore::OptionBool$new(
                "ac_summary",
                ac_summary,
                default=FALSE)
            private$..ac_timepoints <- jmvcore::OptionString$new(
                "ac_timepoints",
                ac_timepoints,
                default="12, 36, 60")
            private$..ac_compare <- jmvcore::OptionBool$new(
                "ac_compare",
                ac_compare,
                default=FALSE)

            self$.addOption(private$..elapsedtime)
            self$.addOption(private$..tint)
            self$.addOption(private$..dxdate)
            self$.addOption(private$..fudate)
            self$.addOption(private$..outcome)
            self$.addOption(private$..outcomeLevel)
            self$.addOption(private$..dod)
            self$.addOption(private$..dooc)
            self$.addOption(private$..awd)
            self$.addOption(private$..awod)
            self$.addOption(private$..explanatory)
            self$.addOption(private$..contexpl)
            self$.addOption(private$..multievent)
            self$.addOption(private$..analysistype)
            self$.addOption(private$..outcomeredefined)
            self$.addOption(private$..timetypedata)
            self$.addOption(private$..timetypeoutput)
            self$.addOption(private$..uselandmark)
            self$.addOption(private$..landmark)
            self$.addOption(private$..calculatedtime)
            self$.addOption(private$..hr)
            self$.addOption(private$..sty)
            self$.addOption(private$..ph_cox)
            self$.addOption(private$..calculateRiskScore)
            self$.addOption(private$..addRiskScore)
            self$.addOption(private$..addRiskGroup)
            self$.addOption(private$..ac)
            self$.addOption(private$..adjexplanatory)
            self$.addOption(private$..km)
            self$.addOption(private$..endplot)
            self$.addOption(private$..byplot)
            self$.addOption(private$..ci95)
            self$.addOption(private$..risktable)
            self$.addOption(private$..censored)
            self$.addOption(private$..pplot)
            self$.addOption(private$..ac_method)
            self$.addOption(private$..ac_summary)
            self$.addOption(private$..ac_timepoints)
            self$.addOption(private$..ac_compare)
        }),
    active = list(
        elapsedtime = function() private$..elapsedtime$value,
        tint = function() private$..tint$value,
        dxdate = function() private$..dxdate$value,
        fudate = function() private$..fudate$value,
        outcome = function() private$..outcome$value,
        outcomeLevel = function() private$..outcomeLevel$value,
        dod = function() private$..dod$value,
        dooc = function() private$..dooc$value,
        awd = function() private$..awd$value,
        awod = function() private$..awod$value,
        explanatory = function() private$..explanatory$value,
        contexpl = function() private$..contexpl$value,
        multievent = function() private$..multievent$value,
        analysistype = function() private$..analysistype$value,
        outcomeredefined = function() private$..outcomeredefined$value,
        timetypedata = function() private$..timetypedata$value,
        timetypeoutput = function() private$..timetypeoutput$value,
        uselandmark = function() private$..uselandmark$value,
        landmark = function() private$..landmark$value,
        calculatedtime = function() private$..calculatedtime$value,
        hr = function() private$..hr$value,
        sty = function() private$..sty$value,
        ph_cox = function() private$..ph_cox$value,
        calculateRiskScore = function() private$..calculateRiskScore$value,
        addRiskScore = function() private$..addRiskScore$value,
        addRiskGroup = function() private$..addRiskGroup$value,
        ac = function() private$..ac$value,
        adjexplanatory = function() private$..adjexplanatory$value,
        km = function() private$..km$value,
        endplot = function() private$..endplot$value,
        byplot = function() private$..byplot$value,
        ci95 = function() private$..ci95$value,
        risktable = function() private$..risktable$value,
        censored = function() private$..censored$value,
        pplot = function() private$..pplot$value,
        ac_method = function() private$..ac_method$value,
        ac_summary = function() private$..ac_summary$value,
        ac_timepoints = function() private$..ac_timepoints$value,
        ac_compare = function() private$..ac_compare$value),
    private = list(
        ..elapsedtime = NA,
        ..tint = NA,
        ..dxdate = NA,
        ..fudate = NA,
        ..outcome = NA,
        ..outcomeLevel = NA,
        ..dod = NA,
        ..dooc = NA,
        ..awd = NA,
        ..awod = NA,
        ..explanatory = NA,
        ..contexpl = NA,
        ..multievent = NA,
        ..analysistype = NA,
        ..outcomeredefined = NA,
        ..timetypedata = NA,
        ..timetypeoutput = NA,
        ..uselandmark = NA,
        ..landmark = NA,
        ..calculatedtime = NA,
        ..hr = NA,
        ..sty = NA,
        ..ph_cox = NA,
        ..calculateRiskScore = NA,
        ..addRiskScore = NA,
        ..addRiskGroup = NA,
        ..ac = NA,
        ..adjexplanatory = NA,
        ..km = NA,
        ..endplot = NA,
        ..byplot = NA,
        ..ci95 = NA,
        ..risktable = NA,
        ..censored = NA,
        ..pplot = NA,
        ..ac_method = NA,
        ..ac_summary = NA,
        ..ac_timepoints = NA,
        ..ac_compare = NA)
)

multisurvivalResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multisurvivalResults",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        text = function() private$.items[["text"]],
        text2 = function() private$.items[["text2"]],
        plot = function() private$.items[["plot"]],
        plot3 = function() private$.items[["plot3"]],
        cox_ph = function() private$.items[["cox_ph"]],
        plot8 = function() private$.items[["plot8"]],
        mydataview = function() private$.items[["mydataview"]],
        riskSummaryTable = function() private$.items[["riskSummaryTable"]],
        riskScoreText = function() private$.items[["riskScoreText"]],
        plotKM = function() private$.items[["plotKM"]],
        riskScoreTable = function() private$.items[["riskScoreTable"]],
        riskScoreMetrics = function() private$.items[["riskScoreMetrics"]],
        calculatedtime = function() private$.items[["calculatedtime"]],
        outcomeredefined = function() private$.items[["outcomeredefined"]],
        addRiskScore = function() private$.items[["addRiskScore"]],
        addRiskGroup = function() private$.items[["addRiskGroup"]],
        mydataview_plot_adj = function() private$.items[["mydataview_plot_adj"]],
        plot_adj = function() private$.items[["plot_adj"]],
        mydataview_calculateAdjustedStats = function() private$.items[["mydataview_calculateAdjustedStats"]],
        adjustedSummaryTable = function() private$.items[["adjustedSummaryTable"]],
        adjustedComparison = function() private$.items[["adjustedComparison"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multivariable Survival Analysis",
                refs=list(
                    "multivariable",
                    "survivaltutorial",
                    "survivalrwnahhas",
                    "ClinicoPathJamoviModule"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do",
                clearWith=list(
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent")))
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Multivariable Survival",
                refs="finalfit",
                clearWith=list(
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent")))
            self$add(jmvcore::Html$new(
                options=options,
                name="text2",
                title="",
                refs="finalfit",
                clearWith=list(
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Hazards Regression Plot",
                width=600,
                height=450,
                renderFun=".plot",
                requiresData=TRUE,
                visible="(hr && sty:t1)",
                refs="finalfit",
                clearWith=list(
                    "hr",
                    "sty",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Hazards Regression Plot",
                width=800,
                height=600,
                renderFun=".plot3",
                requiresData=TRUE,
                visible="(hr && sty:t3)",
                refs="survminer",
                clearWith=list(
                    "hr",
                    "sty",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cox_ph",
                title="Proportional Hazards Assumption",
                visible="(ph_cox)",
                clearWith=list(
                    "explanatory",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "contexpl")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot8",
                title="Proportional Hazards Assumption",
                width=600,
                height=450,
                renderFun=".plot8",
                visible="(ph_cox)",
                requiresData=TRUE,
                clearWith=list(
                    "ph_cox",
                    "endplot",
                    "byplot",
                    "explanatory",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "contexpl")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mydataview",
                title="mydataview"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="riskSummaryTable",
                title="riskSummaryTable"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="riskScoreText",
                title="riskScoreText"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotKM",
                title="Kaplan-Meier",
                width=600,
                height=450,
                renderFun=".plotKM",
                requiresData=TRUE,
                visible="(km)",
                refs="finalfit",
                clearWith=list(
                    "km",
                    "endplot",
                    "byplot",
                    "ci95",
                    "risktable",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "adjexplanatory",
                    "pplot",
                    "censored")))
            self$add(jmvcore::Table$new(
                options=options,
                name="riskScoreTable",
                title="Risk Score Summary",
                visible="(calculateRiskScore)",
                rows=0,
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Risk Group", 
                        `type`="text"),
                    list(
                        `name`="n_patients", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="percent", 
                        `title`="Percent", 
                        `type`="number"),
                    list(
                        `name`="median_score", 
                        `title`="Median Score", 
                        `type`="number"),
                    list(
                        `name`="events", 
                        `title`="Events", 
                        `type`="integer")),
                clearWith=list(
                    "calculateRiskScore",
                    "outcome",
                    "outcomeLevel",
                    "explanatory",
                    "contexpl")))
            self$add(jmvcore::Html$new(
                options=options,
                name="riskScoreMetrics",
                title="Risk Score Model Metrics",
                visible="(calculateRiskScore)",
                clearWith=list(
                    "calculateRiskScore",
                    "outcome",
                    "outcomeLevel",
                    "explanatory",
                    "contexpl")))
            self$add(jmvcore::Output$new(
                options=options,
                name="calculatedtime",
                title="Add Calculated Time to Data",
                varTitle="`Calculated Time in Multivariable Survival Function - from ${ dxdate } to { fudate }`",
                varDescription="Calculated Time from given Dates in Multivariable Survival Analysis",
                clearWith=list(
                    "tint",
                    "dxdate",
                    "fudate")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outcomeredefined",
                title="Add Redefined Outcome to Data",
                varTitle="`Redefined Outcome in Multivariable Survival Function - from ${ outcome } for analysis { analysistype }`",
                varDescription="Redefined Outcome from Outcome based on Analysis Type in Multivariable Survival Analysis",
                clearWith=list(
                    "outcome",
                    "analysistype",
                    "multievent")))
            self$add(jmvcore::Output$new(
                options=options,
                name="addRiskScore",
                title="Add Calculated Risk Score to Data",
                varTitle="`Calculated Risk Score in Multivariable Survival Function`",
                varDescription="Calculated Risk Score Based on Model",
                clearWith=list(
                    "addRiskScore",
                    "calculateRiskScore",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "addRiskGroup")))
            self$add(jmvcore::Output$new(
                options=options,
                name="addRiskGroup",
                title="Add Calculated Risk Group to Data",
                varTitle="`Calculated Risk Group in Multivariable Survival Function`",
                varDescription="Calculated Risk Group Based on Model",
                clearWith=list(
                    "addRiskScore",
                    "calculateRiskScore",
                    "outcome",
                    "outcomeLevel",
                    "overalltime",
                    "explanatory",
                    "contexpl",
                    "fudate",
                    "dxdate",
                    "tint",
                    "multievent",
                    "addRiskGroup")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mydataview_plot_adj",
                title="plot_adj"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot_adj",
                title="Adjusted Survival Plot",
                width=600,
                height=450,
                renderFun=".plot_adj",
                visible="(ac)",
                refs="survminer",
                clearWith=list(
                    "ac",
                    "adjexplanatory",
                    "ci95",
                    "risktable",
                    "ac_method")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mydataview_calculateAdjustedStats",
                title="mydataview_calculateAdjustedStats"))
            self$add(jmvcore::Table$new(
                options=options,
                name="adjustedSummaryTable",
                title="Adjusted Survival Summary",
                visible="(ac_summary)",
                rows=0,
                columns=list(
                    list(
                        `name`="Level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="Timepoint", 
                        `title`="Time", 
                        `type`="integer"),
                    list(
                        `name`="Survival", 
                        `title`="Adjusted Survival", 
                        `type`="number", 
                        `format`="proportion"),
                    list(
                        `name`="SE", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="CI_Lower", 
                        `title`="95% CI Lower", 
                        `type`="number", 
                        `format`="proportion"),
                    list(
                        `name`="CI_Upper", 
                        `title`="95% CI Upper", 
                        `type`="number", 
                        `format`="proportion")),
                clearWith=list(
                    "ac_summary",
                    "ac_timepoints",
                    "ac_method",
                    "adjexplanatory")))
            self$add(jmvcore::Html$new(
                options=options,
                name="adjustedComparison",
                title="Statistical Comparison of Adjusted Curves",
                visible="(ac_compare)",
                clearWith=list(
                    "ac_compare",
                    "ac_method",
                    "adjexplanatory")))}))

multisurvivalBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multisurvivalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jsurvival",
                name = "multisurvival",
                version = c(1,0,0),
                options = options,
                results = multisurvivalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Multivariable Survival Analysis
#'
#' Function for Multivariable Survival Analysis using Cox-regression.
#'
#' @examples
#' \donttest{
#' # example will be added
#'}
#' @param data The data as a data frame.
#' @param elapsedtime .
#' @param tint .
#' @param dxdate .
#' @param fudate .
#' @param outcome .
#' @param outcomeLevel .
#' @param dod .
#' @param dooc .
#' @param awd .
#' @param awod .
#' @param explanatory .
#' @param contexpl .
#' @param multievent .
#' @param analysistype .
#' @param timetypedata select the time type in data
#' @param timetypeoutput select the time type in output
#' @param uselandmark .
#' @param landmark .
#' @param hr .
#' @param sty .
#' @param ph_cox .
#' @param calculateRiskScore .
#' @param ac .
#' @param adjexplanatory .
#' @param km .
#' @param endplot .
#' @param byplot .
#' @param ci95 .
#' @param risktable .
#' @param censored .
#' @param pplot .
#' @param ac_method Method for computing adjusted survival curves
#' @param ac_summary Calculate and display summary statistics for adjusted
#'   curves
#' @param ac_timepoints Timepoints for calculating summary statistics
#'   (comma-separated)
#' @param ac_compare Perform statistical comparison between adjusted curves
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cox_ph} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot8} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mydataview} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$riskSummaryTable} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$riskScoreText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plotKM} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$riskScoreTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$riskScoreMetrics} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$calculatedtime} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outcomeredefined} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$addRiskScore} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$addRiskGroup} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$mydataview_plot_adj} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot_adj} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mydataview_calculateAdjustedStats} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$adjustedSummaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$adjustedComparison} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$riskScoreTable$asDF}
#'
#' \code{as.data.frame(results$riskScoreTable)}
#'
#' @export
multisurvival <- function(
    data,
    elapsedtime,
    tint = FALSE,
    dxdate,
    fudate,
    outcome,
    outcomeLevel,
    dod,
    dooc,
    awd,
    awod,
    explanatory,
    contexpl,
    multievent = FALSE,
    analysistype = "overall",
    timetypedata = "ymd",
    timetypeoutput = "months",
    uselandmark = FALSE,
    landmark = 3,
    hr = FALSE,
    sty = "t1",
    ph_cox = FALSE,
    calculateRiskScore = FALSE,
    ac = FALSE,
    adjexplanatory,
    km = FALSE,
    endplot = 60,
    byplot = 12,
    ci95 = FALSE,
    risktable = FALSE,
    censored = FALSE,
    pplot = TRUE,
    ac_method = "average",
    ac_summary = FALSE,
    ac_timepoints = "12, 36, 60",
    ac_compare = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("multisurvival requires jmvcore to be installed (restart may be required)")

    if ( ! missing(elapsedtime)) elapsedtime <- jmvcore::resolveQuo(jmvcore::enquo(elapsedtime))
    if ( ! missing(dxdate)) dxdate <- jmvcore::resolveQuo(jmvcore::enquo(dxdate))
    if ( ! missing(fudate)) fudate <- jmvcore::resolveQuo(jmvcore::enquo(fudate))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(explanatory)) explanatory <- jmvcore::resolveQuo(jmvcore::enquo(explanatory))
    if ( ! missing(contexpl)) contexpl <- jmvcore::resolveQuo(jmvcore::enquo(contexpl))
    if ( ! missing(adjexplanatory)) adjexplanatory <- jmvcore::resolveQuo(jmvcore::enquo(adjexplanatory))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(elapsedtime), elapsedtime, NULL),
            `if`( ! missing(dxdate), dxdate, NULL),
            `if`( ! missing(fudate), fudate, NULL),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(explanatory), explanatory, NULL),
            `if`( ! missing(contexpl), contexpl, NULL),
            `if`( ! missing(adjexplanatory), adjexplanatory, NULL))

    for (v in explanatory) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in adjexplanatory) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- multisurvivalOptions$new(
        elapsedtime = elapsedtime,
        tint = tint,
        dxdate = dxdate,
        fudate = fudate,
        outcome = outcome,
        outcomeLevel = outcomeLevel,
        dod = dod,
        dooc = dooc,
        awd = awd,
        awod = awod,
        explanatory = explanatory,
        contexpl = contexpl,
        multievent = multievent,
        analysistype = analysistype,
        timetypedata = timetypedata,
        timetypeoutput = timetypeoutput,
        uselandmark = uselandmark,
        landmark = landmark,
        hr = hr,
        sty = sty,
        ph_cox = ph_cox,
        calculateRiskScore = calculateRiskScore,
        ac = ac,
        adjexplanatory = adjexplanatory,
        km = km,
        endplot = endplot,
        byplot = byplot,
        ci95 = ci95,
        risktable = risktable,
        censored = censored,
        pplot = pplot,
        ac_method = ac_method,
        ac_summary = ac_summary,
        ac_timepoints = ac_timepoints,
        ac_compare = ac_compare)

    analysis <- multisurvivalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

