
# This file is automatically generated, you probably don't want to edit this

stagemigrationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "stagemigrationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            oldStage = NULL,
            newStage = NULL,
            survivalTime = NULL,
            event = NULL,
            eventLevel = NULL,
            analysisType = "comprehensive",
            confidenceLevel = 0.95,
            calculateNRI = TRUE,
            nriTimePoints = "12, 24, 60",
            calculateIDI = TRUE,
            performROCAnalysis = TRUE,
            rocTimePoints = "12, 24, 36, 60",
            performDCA = TRUE,
            performCalibration = TRUE,
            performBootstrap = TRUE,
            bootstrapReps = 1000,
            performCrossValidation = FALSE,
            cvFolds = 5,
            clinicalSignificanceThreshold = 0.02,
            nriClinicalThreshold = 0.2,
            performHomogeneityTests = TRUE,
            performTrendTests = TRUE,
            performLikelihoodTests = TRUE,
            calculatePseudoR2 = TRUE,
            showMigrationHeatmap = TRUE,
            showROCComparison = TRUE,
            showCalibrationPlots = TRUE,
            showDecisionCurves = TRUE,
            showForestPlot = TRUE,
            showWillRogersAnalysis = TRUE,
            survivalPlotType = "separate",
            showConfidenceIntervals = TRUE,
            showRiskTables = TRUE,
            plotTimeRange = "auto",
            showClinicalInterpretation = TRUE,
            showStatisticalSummary = TRUE,
            showMethodologyNotes = TRUE,
            includeEffectSizes = TRUE,
            generateExecutiveSummary = TRUE,
            cancerType = "general",
            useOptimismCorrection = TRUE, ...) {

            super$initialize(
                package="jsurvival",
                name="stagemigration",
                requiresData=TRUE,
                ...)

            private$..oldStage <- jmvcore::OptionVariable$new(
                "oldStage",
                oldStage,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..newStage <- jmvcore::OptionVariable$new(
                "newStage",
                newStage,
                suggested=list(
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..survivalTime <- jmvcore::OptionVariable$new(
                "survivalTime",
                survivalTime,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..event <- jmvcore::OptionVariable$new(
                "event",
                event,
                suggested=list(
                    "ordinal",
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..eventLevel <- jmvcore::OptionLevel$new(
                "eventLevel",
                eventLevel,
                variable="(event)")
            private$..analysisType <- jmvcore::OptionList$new(
                "analysisType",
                analysisType,
                options=list(
                    "basic",
                    "standard",
                    "comprehensive",
                    "publication"),
                default="comprehensive")
            private$..confidenceLevel <- jmvcore::OptionNumber$new(
                "confidenceLevel",
                confidenceLevel,
                min=0.8,
                max=0.99,
                default=0.95)
            private$..calculateNRI <- jmvcore::OptionBool$new(
                "calculateNRI",
                calculateNRI,
                default=TRUE)
            private$..nriTimePoints <- jmvcore::OptionString$new(
                "nriTimePoints",
                nriTimePoints,
                default="12, 24, 60")
            private$..calculateIDI <- jmvcore::OptionBool$new(
                "calculateIDI",
                calculateIDI,
                default=TRUE)
            private$..performROCAnalysis <- jmvcore::OptionBool$new(
                "performROCAnalysis",
                performROCAnalysis,
                default=TRUE)
            private$..rocTimePoints <- jmvcore::OptionString$new(
                "rocTimePoints",
                rocTimePoints,
                default="12, 24, 36, 60")
            private$..performDCA <- jmvcore::OptionBool$new(
                "performDCA",
                performDCA,
                default=TRUE)
            private$..performCalibration <- jmvcore::OptionBool$new(
                "performCalibration",
                performCalibration,
                default=TRUE)
            private$..performBootstrap <- jmvcore::OptionBool$new(
                "performBootstrap",
                performBootstrap,
                default=TRUE)
            private$..bootstrapReps <- jmvcore::OptionNumber$new(
                "bootstrapReps",
                bootstrapReps,
                min=100,
                max=2000,
                default=1000)
            private$..performCrossValidation <- jmvcore::OptionBool$new(
                "performCrossValidation",
                performCrossValidation,
                default=FALSE)
            private$..cvFolds <- jmvcore::OptionNumber$new(
                "cvFolds",
                cvFolds,
                min=3,
                max=10,
                default=5)
            private$..clinicalSignificanceThreshold <- jmvcore::OptionNumber$new(
                "clinicalSignificanceThreshold",
                clinicalSignificanceThreshold,
                min=0.01,
                max=0.1,
                default=0.02)
            private$..nriClinicalThreshold <- jmvcore::OptionNumber$new(
                "nriClinicalThreshold",
                nriClinicalThreshold,
                min=0.1,
                max=0.5,
                default=0.2)
            private$..performHomogeneityTests <- jmvcore::OptionBool$new(
                "performHomogeneityTests",
                performHomogeneityTests,
                default=TRUE)
            private$..performTrendTests <- jmvcore::OptionBool$new(
                "performTrendTests",
                performTrendTests,
                default=TRUE)
            private$..performLikelihoodTests <- jmvcore::OptionBool$new(
                "performLikelihoodTests",
                performLikelihoodTests,
                default=TRUE)
            private$..calculatePseudoR2 <- jmvcore::OptionBool$new(
                "calculatePseudoR2",
                calculatePseudoR2,
                default=TRUE)
            private$..showMigrationHeatmap <- jmvcore::OptionBool$new(
                "showMigrationHeatmap",
                showMigrationHeatmap,
                default=TRUE)
            private$..showROCComparison <- jmvcore::OptionBool$new(
                "showROCComparison",
                showROCComparison,
                default=TRUE)
            private$..showCalibrationPlots <- jmvcore::OptionBool$new(
                "showCalibrationPlots",
                showCalibrationPlots,
                default=TRUE)
            private$..showDecisionCurves <- jmvcore::OptionBool$new(
                "showDecisionCurves",
                showDecisionCurves,
                default=TRUE)
            private$..showForestPlot <- jmvcore::OptionBool$new(
                "showForestPlot",
                showForestPlot,
                default=TRUE)
            private$..showWillRogersAnalysis <- jmvcore::OptionBool$new(
                "showWillRogersAnalysis",
                showWillRogersAnalysis,
                default=TRUE)
            private$..survivalPlotType <- jmvcore::OptionList$new(
                "survivalPlotType",
                survivalPlotType,
                options=list(
                    "separate",
                    "sidebyside",
                    "overlay",
                    "keystages"),
                default="separate")
            private$..showConfidenceIntervals <- jmvcore::OptionBool$new(
                "showConfidenceIntervals",
                showConfidenceIntervals,
                default=TRUE)
            private$..showRiskTables <- jmvcore::OptionBool$new(
                "showRiskTables",
                showRiskTables,
                default=TRUE)
            private$..plotTimeRange <- jmvcore::OptionString$new(
                "plotTimeRange",
                plotTimeRange,
                default="auto")
            private$..showClinicalInterpretation <- jmvcore::OptionBool$new(
                "showClinicalInterpretation",
                showClinicalInterpretation,
                default=TRUE)
            private$..showStatisticalSummary <- jmvcore::OptionBool$new(
                "showStatisticalSummary",
                showStatisticalSummary,
                default=TRUE)
            private$..showMethodologyNotes <- jmvcore::OptionBool$new(
                "showMethodologyNotes",
                showMethodologyNotes,
                default=TRUE)
            private$..includeEffectSizes <- jmvcore::OptionBool$new(
                "includeEffectSizes",
                includeEffectSizes,
                default=TRUE)
            private$..generateExecutiveSummary <- jmvcore::OptionBool$new(
                "generateExecutiveSummary",
                generateExecutiveSummary,
                default=TRUE)
            private$..cancerType <- jmvcore::OptionList$new(
                "cancerType",
                cancerType,
                options=list(
                    "general",
                    "lung",
                    "breast",
                    "colorectal",
                    "prostate",
                    "headneck",
                    "melanoma",
                    "other"),
                default="general")
            private$..useOptimismCorrection <- jmvcore::OptionBool$new(
                "useOptimismCorrection",
                useOptimismCorrection,
                default=TRUE)

            self$.addOption(private$..oldStage)
            self$.addOption(private$..newStage)
            self$.addOption(private$..survivalTime)
            self$.addOption(private$..event)
            self$.addOption(private$..eventLevel)
            self$.addOption(private$..analysisType)
            self$.addOption(private$..confidenceLevel)
            self$.addOption(private$..calculateNRI)
            self$.addOption(private$..nriTimePoints)
            self$.addOption(private$..calculateIDI)
            self$.addOption(private$..performROCAnalysis)
            self$.addOption(private$..rocTimePoints)
            self$.addOption(private$..performDCA)
            self$.addOption(private$..performCalibration)
            self$.addOption(private$..performBootstrap)
            self$.addOption(private$..bootstrapReps)
            self$.addOption(private$..performCrossValidation)
            self$.addOption(private$..cvFolds)
            self$.addOption(private$..clinicalSignificanceThreshold)
            self$.addOption(private$..nriClinicalThreshold)
            self$.addOption(private$..performHomogeneityTests)
            self$.addOption(private$..performTrendTests)
            self$.addOption(private$..performLikelihoodTests)
            self$.addOption(private$..calculatePseudoR2)
            self$.addOption(private$..showMigrationHeatmap)
            self$.addOption(private$..showROCComparison)
            self$.addOption(private$..showCalibrationPlots)
            self$.addOption(private$..showDecisionCurves)
            self$.addOption(private$..showForestPlot)
            self$.addOption(private$..showWillRogersAnalysis)
            self$.addOption(private$..survivalPlotType)
            self$.addOption(private$..showConfidenceIntervals)
            self$.addOption(private$..showRiskTables)
            self$.addOption(private$..plotTimeRange)
            self$.addOption(private$..showClinicalInterpretation)
            self$.addOption(private$..showStatisticalSummary)
            self$.addOption(private$..showMethodologyNotes)
            self$.addOption(private$..includeEffectSizes)
            self$.addOption(private$..generateExecutiveSummary)
            self$.addOption(private$..cancerType)
            self$.addOption(private$..useOptimismCorrection)
        }),
    active = list(
        oldStage = function() private$..oldStage$value,
        newStage = function() private$..newStage$value,
        survivalTime = function() private$..survivalTime$value,
        event = function() private$..event$value,
        eventLevel = function() private$..eventLevel$value,
        analysisType = function() private$..analysisType$value,
        confidenceLevel = function() private$..confidenceLevel$value,
        calculateNRI = function() private$..calculateNRI$value,
        nriTimePoints = function() private$..nriTimePoints$value,
        calculateIDI = function() private$..calculateIDI$value,
        performROCAnalysis = function() private$..performROCAnalysis$value,
        rocTimePoints = function() private$..rocTimePoints$value,
        performDCA = function() private$..performDCA$value,
        performCalibration = function() private$..performCalibration$value,
        performBootstrap = function() private$..performBootstrap$value,
        bootstrapReps = function() private$..bootstrapReps$value,
        performCrossValidation = function() private$..performCrossValidation$value,
        cvFolds = function() private$..cvFolds$value,
        clinicalSignificanceThreshold = function() private$..clinicalSignificanceThreshold$value,
        nriClinicalThreshold = function() private$..nriClinicalThreshold$value,
        performHomogeneityTests = function() private$..performHomogeneityTests$value,
        performTrendTests = function() private$..performTrendTests$value,
        performLikelihoodTests = function() private$..performLikelihoodTests$value,
        calculatePseudoR2 = function() private$..calculatePseudoR2$value,
        showMigrationHeatmap = function() private$..showMigrationHeatmap$value,
        showROCComparison = function() private$..showROCComparison$value,
        showCalibrationPlots = function() private$..showCalibrationPlots$value,
        showDecisionCurves = function() private$..showDecisionCurves$value,
        showForestPlot = function() private$..showForestPlot$value,
        showWillRogersAnalysis = function() private$..showWillRogersAnalysis$value,
        survivalPlotType = function() private$..survivalPlotType$value,
        showConfidenceIntervals = function() private$..showConfidenceIntervals$value,
        showRiskTables = function() private$..showRiskTables$value,
        plotTimeRange = function() private$..plotTimeRange$value,
        showClinicalInterpretation = function() private$..showClinicalInterpretation$value,
        showStatisticalSummary = function() private$..showStatisticalSummary$value,
        showMethodologyNotes = function() private$..showMethodologyNotes$value,
        includeEffectSizes = function() private$..includeEffectSizes$value,
        generateExecutiveSummary = function() private$..generateExecutiveSummary$value,
        cancerType = function() private$..cancerType$value,
        useOptimismCorrection = function() private$..useOptimismCorrection$value),
    private = list(
        ..oldStage = NA,
        ..newStage = NA,
        ..survivalTime = NA,
        ..event = NA,
        ..eventLevel = NA,
        ..analysisType = NA,
        ..confidenceLevel = NA,
        ..calculateNRI = NA,
        ..nriTimePoints = NA,
        ..calculateIDI = NA,
        ..performROCAnalysis = NA,
        ..rocTimePoints = NA,
        ..performDCA = NA,
        ..performCalibration = NA,
        ..performBootstrap = NA,
        ..bootstrapReps = NA,
        ..performCrossValidation = NA,
        ..cvFolds = NA,
        ..clinicalSignificanceThreshold = NA,
        ..nriClinicalThreshold = NA,
        ..performHomogeneityTests = NA,
        ..performTrendTests = NA,
        ..performLikelihoodTests = NA,
        ..calculatePseudoR2 = NA,
        ..showMigrationHeatmap = NA,
        ..showROCComparison = NA,
        ..showCalibrationPlots = NA,
        ..showDecisionCurves = NA,
        ..showForestPlot = NA,
        ..showWillRogersAnalysis = NA,
        ..survivalPlotType = NA,
        ..showConfidenceIntervals = NA,
        ..showRiskTables = NA,
        ..plotTimeRange = NA,
        ..showClinicalInterpretation = NA,
        ..showStatisticalSummary = NA,
        ..showMethodologyNotes = NA,
        ..includeEffectSizes = NA,
        ..generateExecutiveSummary = NA,
        ..cancerType = NA,
        ..useOptimismCorrection = NA)
)

stagemigrationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "stagemigrationResults",
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        migrationSummary = function() private$.items[["migrationSummary"]],
        stageDistribution = function() private$.items[["stageDistribution"]],
        migrationTable = function() private$.items[["migrationTable"]],
        survivalComparison = function() private$.items[["survivalComparison"]],
        stagingPerformance = function() private$.items[["stagingPerformance"]],
        migrationPlot = function() private$.items[["migrationPlot"]],
        survivalPlot = function() private$.items[["survivalPlot"]],
        concordancePlot = function() private$.items[["concordancePlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Stage Migration Analysis",
                refs=list(
                    "willrogers1985",
                    "stagemigration2009",
                    "tnmstaging2017",
                    "stagingbias2004",
                    "survival",
                    "survminer",
                    "ggalluvial"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="Welcome",
                clearWith=list(
                    "oldStage",
                    "newStage",
                    "survivalTime",
                    "event",
                    "eventLevel")))
            self$add(jmvcore::Table$new(
                options=options,
                name="migrationSummary",
                title="Migration Summary",
                clearWith=list(
                    "oldStage",
                    "newStage",
                    "survivalTime",
                    "event",
                    "eventLevel"),
                columns=list(
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="stageDistribution",
                title="Stage Distribution Comparison",
                clearWith=list(
                    "oldStage",
                    "newStage",
                    "survivalTime",
                    "event",
                    "eventLevel"),
                columns=list(
                    list(
                        `name`="stage", 
                        `title`="Stage", 
                        `type`="text"),
                    list(
                        `name`="oldCount", 
                        `title`="Original Count", 
                        `type`="integer"),
                    list(
                        `name`="oldPct", 
                        `title`="Original %", 
                        `type`="text"),
                    list(
                        `name`="newCount", 
                        `title`="New Count", 
                        `type`="integer"),
                    list(
                        `name`="newPct", 
                        `title`="New %", 
                        `type`="text"),
                    list(
                        `name`="change", 
                        `title`="Change", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="migrationTable",
                title="Stage Migration Matrix",
                clearWith=list(
                    "oldStage",
                    "newStage",
                    "survivalTime",
                    "event",
                    "eventLevel"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="survivalComparison",
                title="Prognostic Performance Comparison",
                clearWith=list(
                    "oldStage",
                    "newStage",
                    "survivalTime",
                    "event",
                    "eventLevel"),
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="oldValue", 
                        `title`="Original System", 
                        `type`="text"),
                    list(
                        `name`="newValue", 
                        `title`="New System", 
                        `type`="text"),
                    list(
                        `name`="change", 
                        `title`="Change", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="stagingPerformance",
                title="Will Rogers Phenomenon Analysis",
                visible="(showWillRogers)",
                clearWith=list(
                    "oldStage",
                    "newStage",
                    "survivalTime",
                    "event",
                    "eventLevel",
                    "showWillRogers"),
                columns=list(
                    list(
                        `name`="stage", 
                        `title`="Stage", 
                        `type`="text"),
                    list(
                        `name`="stayedN", 
                        `title`="Unchanged N", 
                        `type`="integer"),
                    list(
                        `name`="stayedMedian", 
                        `title`="Unchanged Median", 
                        `type`="text"),
                    list(
                        `name`="migratedN", 
                        `title`="Migrated N", 
                        `type`="integer"),
                    list(
                        `name`="migratedMedian", 
                        `title`="Migrated Median", 
                        `type`="text"),
                    list(
                        `name`="pValue", 
                        `title`="p-value", 
                        `type`="text", 
                        `format`="pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="migrationPlot",
                title="Stage Migration Flow",
                width=700,
                height=500,
                renderFun=".migrationPlot",
                visible="(plotMigration)",
                clearWith=list(
                    "oldStage",
                    "newStage",
                    "survivalTime",
                    "event",
                    "eventLevel",
                    "plotMigration")))
            self$add(jmvcore::Image$new(
                options=options,
                name="survivalPlot",
                title="Survival Comparison",
                width=800,
                height=600,
                renderFun=".survivalPlot",
                visible="(plotMigration)",
                clearWith=list(
                    "oldStage",
                    "newStage",
                    "survivalTime",
                    "event",
                    "eventLevel",
                    "plotMigration",
                    "survivalPlotType",
                    "showCI")))
            self$add(jmvcore::Image$new(
                options=options,
                name="concordancePlot",
                title="Concordance Index Comparison",
                width=600,
                height=400,
                renderFun=".concordancePlot",
                visible="(plotMigration)",
                clearWith=list(
                    "oldStage",
                    "newStage",
                    "survivalTime",
                    "event",
                    "eventLevel",
                    "plotMigration")))}))

stagemigrationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "stagemigrationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jsurvival",
                name = "stagemigration",
                version = c(0,0,3),
                options = options,
                results = stagemigrationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Advanced TNM Stage Migration Analysis
#'
#' Comprehensive analysis for validating TNM staging system improvements using 
#' state-of-the-art  statistical methods. This analysis provides pathologists 
#' with robust tools to evaluate whether  a new staging system provides 
#' superior prognostic discrimination compared to existing systems.
#' Includes advanced metrics: Net Reclassification Improvement (NRI), 
#' Integrated Discrimination  Improvement (IDI), time-dependent ROC analysis, 
#' decision curve analysis, bootstrap validation,  and comprehensive clinical 
#' interpretation guidance.
#'
#' @examples
#' \donttest{
#' # Example analyzing TNM staging system migration:
#' # stagemigration(
#' #   data = cancer_cohort,
#' #   oldStage = "tnm7_stage",
#' #   newStage = "tnm8_stage",
#' #   survivalTime = "os_months",
#' #   event = "death_status",
#' #   eventLevel = "Dead",
#' #   analysisType = "comprehensive",
#' #   calculateNRI = TRUE,
#' #   calculateIDI = TRUE,
#' #   performBootstrap = TRUE,
#' #   bootstrapReps = 1000
#' # )
#'}
#' @param data The dataset containing staging and survival information for TNM
#'   validation analysis.
#' @param oldStage The original staging variable (e.g., TNM 7th edition, AJCC
#'   7th edition). Should be coded as ordered factor with appropriate stage
#'   levels.
#' @param newStage The proposed new staging variable (e.g., TNM 8th edition,
#'   revised staging). Should use the same coding structure as the original
#'   staging system.
#' @param survivalTime Time to event or censoring in consistent units (months
#'   recommended). For overall survival analysis, use time from diagnosis to
#'   death or last follow-up.
#' @param event Event indicator (1 = event occurred, 0 = censored) or factor
#'   with event levels. For overall survival, event = death from any cause.
#' @param eventLevel The level indicating event occurrence when using factor
#'   variables.
#' @param analysisType Determines the scope of statistical analysis performed.
#'   Comprehensive analysis includes all available methods for thorough staging
#'   system validation.
#' @param confidenceLevel Confidence level for all confidence intervals and
#'   hypothesis tests.
#' @param calculateNRI Calculate Net Reclassification Improvement to quantify
#'   improvement in  risk classification between staging systems. Essential for
#'   staging validation.
#' @param nriTimePoints Comma-separated time points for NRI calculation (e.g.,
#'   "12, 24, 60" for  1, 2, and 5-year survival). Use clinically relevant time
#'   points.
#' @param calculateIDI Calculate Integrated Discrimination Improvement to
#'   measure improvement  in risk prediction accuracy between staging systems.
#' @param performROCAnalysis Perform time-dependent ROC analysis to compare
#'   discriminative ability of staging systems over time.
#' @param rocTimePoints Time points for ROC analysis. Should include
#'   clinically important survival milestones for the specific cancer type.
#' @param performDCA Perform Decision Curve Analysis to assess clinical
#'   utility and net benefit of the new staging system for clinical decision
#'   making.
#' @param performCalibration Assess calibration of risk predictions from both
#'   staging systems. Important for validating accuracy of survival predictions.
#' @param performBootstrap Perform bootstrap validation with optimism
#'   correction to assess internal validity of results. Recommended for all
#'   staging validation studies.
#' @param bootstrapReps Number of bootstrap repetitions for internal
#'   validation.  1000 repetitions recommended for stable results.
#' @param performCrossValidation Perform k-fold cross-validation for
#'   additional validation. Computationally intensive but provides robust
#'   validation.
#' @param cvFolds Number of folds for cross-validation when enabled.
#' @param clinicalSignificanceThreshold Minimum improvement in C-index
#'   considered clinically significant. Default 0.02 based on oncology
#'   literature recommendations.
#' @param nriClinicalThreshold Minimum NRI improvement considered clinically
#'   meaningful. Default 0.20 (20\% net reclassification improvement).
#' @param performHomogeneityTests Test homogeneity within stages and monotonic
#'   trend across stages. Essential for validating stage ordering and grouping.
#' @param performTrendTests Test for monotonic trend in survival across stage
#'   levels. Validates that higher stages consistently have worse prognosis.
#' @param performLikelihoodTests Perform formal likelihood ratio tests
#'   comparing nested staging models. Provides statistical significance testing
#'   for staging improvement.
#' @param calculatePseudoR2 Calculate multiple pseudo R-squared measures for
#'   model comparison (Nagelkerke, McFadden, Cox-Snell).
#' @param showMigrationHeatmap Display detailed heatmap showing migration
#'   patterns between staging systems.
#' @param showROCComparison Display time-dependent ROC curves comparing
#'   staging systems.
#' @param showCalibrationPlots Display calibration plots for both staging
#'   systems.
#' @param showDecisionCurves Display decision curves showing net benefit of
#'   staging systems.
#' @param showForestPlot Display forest plot with stage-specific hazard ratios
#'   and confidence intervals.
#' @param showWillRogersAnalysis Detailed analysis of Will Rogers phenomenon
#'   with survival comparisons between migrated and non-migrated patients within
#'   stages.
#' @param survivalPlotType Controls display of survival curves for staging
#'   system comparison.
#' @param showConfidenceIntervals Display confidence intervals around survival
#'   curves and other estimates.
#' @param showRiskTables Display at-risk tables below survival curves.
#' @param plotTimeRange Maximum time for survival plots. Use "auto" for
#'   automatic range or specify maximum months (e.g., "60" for 5-year
#'   follow-up).
#' @param showClinicalInterpretation Display comprehensive clinical
#'   interpretation of all statistical results with guidance for staging system
#'   adoption decisions.
#' @param showStatisticalSummary Display comprehensive table summarizing all
#'   statistical comparisons.
#' @param showMethodologyNotes Display detailed notes on statistical methods
#'   used and their interpretation.
#' @param includeEffectSizes Calculate and display effect sizes for all
#'   comparisons to assess practical significance beyond statistical
#'   significance.
#' @param generateExecutiveSummary Generate executive summary with key
#'   findings and recommendations for clinical and research stakeholders.
#' @param cancerType Optional cancer type specification for customized
#'   thresholds and  interpretation guidelines based on cancer-specific
#'   literature.
#' @param useOptimismCorrection Apply optimism correction to performance
#'   metrics using bootstrap validation to avoid overly optimistic estimates.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$migrationSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$stageDistribution} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$migrationTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$survivalComparison} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$stagingPerformance} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$migrationPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$survivalPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$concordancePlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$migrationSummary$asDF}
#'
#' \code{as.data.frame(results$migrationSummary)}
#'
#' @export
stagemigration <- function(
    data,
    oldStage,
    newStage,
    survivalTime,
    event,
    eventLevel,
    analysisType = "comprehensive",
    confidenceLevel = 0.95,
    calculateNRI = TRUE,
    nriTimePoints = "12, 24, 60",
    calculateIDI = TRUE,
    performROCAnalysis = TRUE,
    rocTimePoints = "12, 24, 36, 60",
    performDCA = TRUE,
    performCalibration = TRUE,
    performBootstrap = TRUE,
    bootstrapReps = 1000,
    performCrossValidation = FALSE,
    cvFolds = 5,
    clinicalSignificanceThreshold = 0.02,
    nriClinicalThreshold = 0.2,
    performHomogeneityTests = TRUE,
    performTrendTests = TRUE,
    performLikelihoodTests = TRUE,
    calculatePseudoR2 = TRUE,
    showMigrationHeatmap = TRUE,
    showROCComparison = TRUE,
    showCalibrationPlots = TRUE,
    showDecisionCurves = TRUE,
    showForestPlot = TRUE,
    showWillRogersAnalysis = TRUE,
    survivalPlotType = "separate",
    showConfidenceIntervals = TRUE,
    showRiskTables = TRUE,
    plotTimeRange = "auto",
    showClinicalInterpretation = TRUE,
    showStatisticalSummary = TRUE,
    showMethodologyNotes = TRUE,
    includeEffectSizes = TRUE,
    generateExecutiveSummary = TRUE,
    cancerType = "general",
    useOptimismCorrection = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("stagemigration requires jmvcore to be installed (restart may be required)")

    if ( ! missing(oldStage)) oldStage <- jmvcore::resolveQuo(jmvcore::enquo(oldStage))
    if ( ! missing(newStage)) newStage <- jmvcore::resolveQuo(jmvcore::enquo(newStage))
    if ( ! missing(survivalTime)) survivalTime <- jmvcore::resolveQuo(jmvcore::enquo(survivalTime))
    if ( ! missing(event)) event <- jmvcore::resolveQuo(jmvcore::enquo(event))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(oldStage), oldStage, NULL),
            `if`( ! missing(newStage), newStage, NULL),
            `if`( ! missing(survivalTime), survivalTime, NULL),
            `if`( ! missing(event), event, NULL))

    for (v in oldStage) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in newStage) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- stagemigrationOptions$new(
        oldStage = oldStage,
        newStage = newStage,
        survivalTime = survivalTime,
        event = event,
        eventLevel = eventLevel,
        analysisType = analysisType,
        confidenceLevel = confidenceLevel,
        calculateNRI = calculateNRI,
        nriTimePoints = nriTimePoints,
        calculateIDI = calculateIDI,
        performROCAnalysis = performROCAnalysis,
        rocTimePoints = rocTimePoints,
        performDCA = performDCA,
        performCalibration = performCalibration,
        performBootstrap = performBootstrap,
        bootstrapReps = bootstrapReps,
        performCrossValidation = performCrossValidation,
        cvFolds = cvFolds,
        clinicalSignificanceThreshold = clinicalSignificanceThreshold,
        nriClinicalThreshold = nriClinicalThreshold,
        performHomogeneityTests = performHomogeneityTests,
        performTrendTests = performTrendTests,
        performLikelihoodTests = performLikelihoodTests,
        calculatePseudoR2 = calculatePseudoR2,
        showMigrationHeatmap = showMigrationHeatmap,
        showROCComparison = showROCComparison,
        showCalibrationPlots = showCalibrationPlots,
        showDecisionCurves = showDecisionCurves,
        showForestPlot = showForestPlot,
        showWillRogersAnalysis = showWillRogersAnalysis,
        survivalPlotType = survivalPlotType,
        showConfidenceIntervals = showConfidenceIntervals,
        showRiskTables = showRiskTables,
        plotTimeRange = plotTimeRange,
        showClinicalInterpretation = showClinicalInterpretation,
        showStatisticalSummary = showStatisticalSummary,
        showMethodologyNotes = showMethodologyNotes,
        includeEffectSizes = includeEffectSizes,
        generateExecutiveSummary = generateExecutiveSummary,
        cancerType = cancerType,
        useOptimismCorrection = useOptimismCorrection)

    analysis <- stagemigrationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

