
# This file is automatically generated, you probably don't want to edit this

timeintervalOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "timeintervalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            time = NULL,
            event = NULL,
            expl = NULL, ...) {

            super$initialize(
                package='jsurvival',
                name='timeinterval',
                requiresData=TRUE,
                ...)

            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time)
            private$..event <- jmvcore::OptionVariable$new(
                "event",
                event)
            private$..expl <- jmvcore::OptionVariables$new(
                "expl",
                expl)

            self$.addOption(private$..time)
            self$.addOption(private$..event)
            self$.addOption(private$..expl)
        }),
    active = list(
        time = function() private$..time$value,
        event = function() private$..event$value,
        expl = function() private$..expl$value),
    private = list(
        ..time = NA,
        ..event = NA,
        ..expl = NA)
)

timeintervalResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text1 = function() private$.items[["text1"]],
        text1html = function() private$.items[["text1html"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Time Interval")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title="denemeler"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1html",
                title="fit"))}))

timeintervalBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "timeintervalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jsurvival',
                name = 'timeinterval',
                version = c(1,0,0),
                options = options,
                results = timeintervalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Time Interval
#'
#' 
#' @param data .
#' @param time .
#' @param event .
#' @param expl .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text1html} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
timeinterval <- function(
    data,
    time,
    event,
    expl) {

    if ( ! requireNamespace('jmvcore'))
        stop('timeinterval requires jmvcore to be installed (restart may be required)')

    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if ( ! missing(event)) event <- jmvcore::resolveQuo(jmvcore::enquo(event))
    if ( ! missing(expl)) expl <- jmvcore::resolveQuo(jmvcore::enquo(expl))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(time), time, NULL),
            `if`( ! missing(event), event, NULL),
            `if`( ! missing(expl), expl, NULL))


    options <- timeintervalOptions$new(
        time = time,
        event = event,
        expl = expl)

    analysis <- timeintervalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
